# HarvestGuard — Data Exploration

Wave 1 (2011-12) LSMS-ISA Ethiopia data. Column names are coded (e.g. `ph_s9q01`) — no codebook is available yet, so this notebook explores structure and value ranges blind, without assuming what each column means. Goal: find the post-harvest loss variable(s) by inspection.

In [1]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", 100)

DATA_DIR = Path("../data/raw/ETH_2011_ERSS_v02_M_CSV")
sorted(p.name for p in DATA_DIR.glob("*.csv"))

['cons_agg_w1.csv',
 'et_local_area_unit_conversion.csv',
 'food_cf_wave1.csv',
 'pub_eth_householdgeovariables_y1.csv',
 'pub_eth_plotgeovariables_y1.csv',
 'sect10_hh_w1.csv',
 'sect10_ph_w1.csv',
 'sect10a1_com_w1.csv',
 'sect10a2_com_w1.csv',
 'sect10b1_com_w1.csv',
 'sect10b2_com_w1.csv',
 'sect11_ph_w1.csv',
 'sect11a_hh_w1.csv',
 'sect11b_hh_w1.csv',
 'sect11c_hh_w1.csv',
 'sect12_hh_w1.csv',
 'sect12_ph_w1.csv',
 'sect13_hh_w1.csv',
 'sect14a_hh_w1.csv',
 'sect14b_hh_w1.csv',
 'sect1_hh_w1.csv',
 'sect1_ls_w1.csv',
 'sect1_ph_w1.csv',
 'sect1_pp_w1.csv',
 'sect1a_com_w1.csv',
 'sect1b_com_w1.csv',
 'sect2_com_w1.csv',
 'sect2_hh_w1.csv',
 'sect2_pp_w1.csv',
 'sect3_com_w1.csv',
 'sect3_hh_w1.csv',
 'sect3_pp_w1.csv',
 'sect3_rca_pp_w1.csv',
 'sect3_rcb_pp_w1.csv',
 'sect4_com_w1.csv',
 'sect4_hh_w1.csv',
 'sect4_pp_w1.csv',
 'sect5_com_w1.csv',
 'sect5_pp_w1.csv',
 'sect5a_hh_w1.csv',
 'sect5b_hh_w1.csv',
 'sect5c1_hh_w1.csv',
 'sect5c2_hh_w1.csv',
 'sect6_com_w1.csv',
 'sect6a_hh_w1.csv',
 'sect6b_hh_w1.csv',
 'sect7_com_w1.csv',
 'sect7_hh_w1.csv',
 'sect7_pp_w1.csv',
 'sect8_com_w1.csv',
 'sect8_hh_w1.csv',
 'sect8a_ls_w1.csv',
 'sect8b_ls_w1.csv',
 'sect8c_ls_w1.csv',
 'sect9_com_w1.csv',
 'sect9_hh_w1.csv',
 'sect9_ph_w1.csv',
 'sect_cover_hh_w1.csv',
 'sect_cover_ls_w1.csv',
 'sect_cover_ph_w1.csv',
 'sect_cover_pp_w1.csv',
 'sect_nr_ph_w1.csv',
 'sect_nr_pp_w1.csv']

## Post-harvest (`_ph_`) sections

These are the most likely candidates for loss-related data. Load each and inspect shape, dtypes, and a sample.

In [2]:
ph_files = sorted(DATA_DIR.glob("*_ph_w1.csv"))
[p.name for p in ph_files]

['sect10_ph_w1.csv',
 'sect11_ph_w1.csv',
 'sect12_ph_w1.csv',
 'sect1_ph_w1.csv',
 'sect9_ph_w1.csv',
 'sect_cover_ph_w1.csv',
 'sect_nr_ph_w1.csv']

In [3]:
ph_frames = {p.stem: pd.read_csv(p) for p in ph_files}

for name, df in ph_frames.items():
    print(f"{name:25s} shape={df.shape}")

sect10_ph_w1              shape=(21249, 64)
sect11_ph_w1              shape=(9226, 58)
sect12_ph_w1              shape=(7872, 42)
sect1_ph_w1               shape=(16831, 18)
sect9_ph_w1               shape=(7750, 36)
sect_cover_ph_w1          shape=(3049, 109)
sect_nr_ph_w1             shape=(4220, 15)

### Section 9 — PH (storage/loss candidate)

In [4]:
df9 = ph_frames["sect9_ph_w1"]
df9.head()

,holder_id,household_id,ea_id,rural,pw,parcel_id,field_id,saq01,saq02,saq03,saq04,saq05,saq06,ph_saq07,crop_name,crop_code,ph_s9q01,ph_s9q02_a,ph_s9q02_b,ph_s9q03_a,ph_s9q03_b,ph_s9q04_a,ph_s9q04_b,ph_s9q05_a,ph_s9q05_b,ph_s9q06,ph_s9q07,ph_s9q08_a,ph_s9q08_b,ph_s9q09,ph_s9q10,ph_s9q11,ph_s9q12_a,ph_s9q12_b,ph_s9q13_a,ph_s9q13_b
0,101010160100201,1010101601002,1010101601,1,2236.134521,1,4,1,1,1,16,1,2,1,SORGHUM,6.0,1.0,30.0,2.0,0.0,900.0,15.0,3.0,0.0,810.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,600.0,0.0,2.0,3.0
1,101010160100202,1010101601002,1010101601,1,2236.134521,1,2,1,1,1,16,1,2,2,MILLET,3.0,1.0,8.0,2.0,0.0,200.0,23.0,2.0,0.0,200.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,200.0,0.0,2.0,2.0
2,101010160101701,1010101601017,1010101601,1,2236.134521,2,1,1,1,1,16,1,17,1,MILLET,3.0,1.0,18.0,2.0,0.0,480.0,3.0,3.0,0.0,470.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,80.0,0.0,2.0,3.0
3,101010160101701,1010101601017,1010101601,1,2236.134521,3,1,1,1,1,16,1,17,1,SORGHUM,6.0,1.0,2.0,3.0,1.0,30.0,17.0,3.0,0.0,950.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,600.0,0.0,2.0,3.0
4,101010160110101,1010101601101,1010101601,1,2236.134521,1,5,1,1,1,16,1,101,1,MILLET,3.0,1.0,15.0,3.0,0.0,490.0,30.0,3.0,0.0,480.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,100.0,0.0,2.0,6.0

In [5]:
df9.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
holder_id,7750.0,NaN,NaN,NaN,470209140385402.5,244880499217663.71875,101010160100201.0,304160020406201.0,408120240109401.0,704040090314901.0,1501020310208701.0
household_id,7750.0,NaN,NaN,NaN,4702091403854.013672,2448804992176.636719,1010101601002.0,3041600204062.0,4081202401094.0,7040400903149.0,15010203102087.0
ea_id,7750.0,NaN,NaN,NaN,4702091403.778193,2448804992.17909,1010101601.0,3041600204.0,4081202401.0,7040400903.0,15010203102.0
rural,7750.0,NaN,NaN,NaN,0.98671,0.114522,0.0,1.0,1.0,1.0,1.0
pw,7750.0,NaN,NaN,NaN,4426.132048,3037.32048,138.915131,2186.578125,4100.652344,6447.219727,17094.660156
parcel_id,7750.0,NaN,NaN,NaN,2.312645,1.930508,1.0,1.0,2.0,3.0,18.0
field_id,7750.0,NaN,NaN,NaN,4.064387,4.651666,1.0,1.0,2.0,5.0,171.0
saq01,7750.0,NaN,NaN,NaN,4.636645,2.437946,1.0,3.0,4.0,7.0,15.0
saq02,7750.0,NaN,NaN,NaN,6.490323,5.123822,1.0,2.0,5.0,10.0,21.0
saq03,7750.0,NaN,NaN,NaN,5.417677,4.278638,1.0,2.0,4.0,8.0,21.0
saq04,7750.0,NaN,NaN,NaN,12.45729,11.315142,1.0,6.0,10.0,17.0,403.0
saq05,7750.0,NaN,NaN,NaN,3.210452,2.4569,1.0,2.0,3.0,4.0,17.0
saq06,7750.0,NaN,NaN,NaN,75.820903,55.116327,1.0,28.0,69.0,113.0,572.0
ph_saq07,7750.0,NaN,NaN,NaN,1.027355,0.269832,1.0,1.0,1.0,1.0,12.0
crop_name,4351,43,MAIZE,828,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crop_code,7746.0,NaN,NaN,NaN,22.072424,26.459417,1.0,6.0,8.0,27.0,120.0
ph_s9q01,5069.0,NaN,NaN,NaN,1.317617,0.465595,1.0,1.0,1.0,2.0,2.0
ph_s9q02_a,3412.0,NaN,NaN,NaN,14.596717,8.20335,1.0,8.0,14.0,21.0,30.0
ph_s9q02_b,3409.0,NaN,NaN,NaN,2.819595,0.973844,0.0,2.0,3.0,3.0,20.0
ph_s9q03_a,2955.0,NaN,NaN,NaN,0.341117,1.305443,0.0,0.0,0.0,0.0,30.0
ph_s9q03_b,3399.0,NaN,NaN,NaN,399.088555,258.532386,0.0,190.0,360.0,580.0,990.0
ph_s9q04_a,3339.0,NaN,NaN,NaN,16.700509,8.948098,0.0,9.0,17.0,25.0,33.0
ph_s9q04_b,3338.0,NaN,NaN,NaN,3.273817,1.322647,0.0,3.0,3.0,4.0,40.0
ph_s9q05_a,2890.0,NaN,NaN,NaN,0.263322,1.920775,0.0,0.0,0.0,0.0,100.0
ph_s9q05_b,3336.0,NaN,NaN,NaN,393.28777,261.18708,0.0,180.0,350.0,580.0,990.0
ph_s9q06,4092.0,NaN,NaN,NaN,1.891984,0.326555,1.0,2.0,2.0,2.0,8.0
ph_s9q07,4028.0,NaN,NaN,NaN,1.87711,0.328351,1.0,2.0,2.0,2.0,2.0
ph_s9q08_a,478.0,NaN,NaN,NaN,7.48954,64.374322,1.0,2.0,2.0,5.0,999.0
ph_s9q08_b,244.0,NaN,NaN,NaN,240.139344,424.635323,1.0,2.0,4.0,10.0,999.0
ph_s9q09,4293.0,NaN,NaN,NaN,1.567668,0.495458,1.0,1.0,2.0,2.0,2.0
ph_s9q10,1831.0,NaN,NaN,NaN,5.922447,6.071657,1.0,2.0,3.0,9.0,99.0
ph_s9q11,1830.0,NaN,NaN,NaN,45.343716,26.99777,2.0,25.0,40.0,60.0,100.0
ph_s9q12_a,4052.0,NaN,NaN,NaN,161.404492,354.324644,0.0,18.0,65.0,200.0,9500.0
ph_s9q12_b,3918.0,NaN,NaN,NaN,63.921388,181.42074,0.0,0.0,0.0,0.0,970.0
ph_s9q13_a,4006.0,NaN,NaN,NaN,2.728657,1.00362,0.0,2.0,3.0,3.0,23.0
ph_s9q13_b,3972.0,NaN,NaN,NaN,3.108761,0.997985,1.0,2.0,3.0,4.0,23.0

In [6]:
df9["crop_name"].value_counts()

crop_name
MAIZE             828
TEFF              512
SORGHUM           483
BARLEY            352
WHEAT             348
HORSE BEANS       282
HARICOT BEANS     245
MILLET            183
FIELD PEAS        147
LINESEED          126
NUEG              116
RAPE SEED          99
SESAME             95
CHICK PEAS         93
LENTILS            76
GROUND NUTS        68
FENUGREEK          62
VETCH              55
SUNFLOWER          32
RED PEPPER         24
GIBTO              21
POTATOES           13
SOYA BEANS         12
OATS               11
OTHER LAND         10
RICE               10
PUMPKINS            8
ONION               6
GESHO               6
GREEN PEPPER        5
GARLIC              3
ENSET               3
KALE                3
SUGAR CANE          2
OTHER OIL SEED      2
COTTON SEED         2
ROMAN               2
OTHER CEREAL        1
COTTON              1
CHAT                1
OTHER SPICES        1
SWEET POTATO        1
COFFEE              1
Name: count, dtype: int64

### Section 11 — PH (utilization/disposition candidate)

In [7]:
df11 = ph_frames["sect11_ph_w1"]
df11.head()

,holder_id,household_id,ea_id,rural,pw,saq01,saq02,saq03,saq04,saq05,saq06,ph_saq07,crop_name,crop_code,ph_s11q01,ph_s11q02_a,ph_s11q02_b,ph_s11q03_a,ph_s11q03_b,ph_s11q04_a,ph_s11q04_b,ph_s11q05_a,ph_s11q05_b,ph_s11q06_a,ph_s11q06_b,ph_s11q07,ph_s11q08,ph_s11q09,ph_s11q10_a,ph_s11q10_b,ph_s11q11_a,ph_s11q11_b,ph_s11q12_a,ph_s11q12_b,ph_s11q13_a,ph_s11q13_b,ph_s11q14_a,ph_s11q14_b,ph_s11q15_a,ph_s11q15_b,ph_s11q15_c,ph_s11q16_a,ph_s11q16_b,ph_s11q17,ph_s11q18,ph_s11q19_a,ph_s11q19_b,ph_s11q20_a,ph_s11q20_b,ph_s11q21_a,ph_s11q21_b,ph_s11q22_a,ph_s11q22_b,ph_s11q22_c,ph_s11q22_d,ph_s11q22_e,ph_s11q22_f,ph_s11q22_g
0,101010160100201,1010101601002,1010101601,1,2236.134521,1,1,1,16,1,2,1,MAIZE,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,400.0,0.0,4.0,NaN,1.0,3.0,95.0,5.0,0.0,0.0,0.0,0.0,100.0
1,101010160100201,1010101601002,1010101601,1,2236.134521,1,1,1,16,1,2,1,MILLET,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,60.0,0.0,4.0,NaN,1.0,3.0,95.0,5.0,0.0,0.0,0.0,0.0,100.0
2,101010160100201,1010101601002,1010101601,1,2236.134521,1,1,1,16,1,2,1,SORGHUM,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,NaN,0.0,0.0,0.0,NaN,NaN,1.0,3.0,18.0,0.0,4.0,NaN,1.0,3.0,95.0,5.0,0.0,0.0,0.0,0.0,100.0
3,101010160101701,1010101601017,1010101601,1,2236.134521,1,1,1,16,1,17,1,MAIZE,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,3.0,0.0,4.0,NaN,1.0,3.0,95.0,5.0,0.0,0.0,0.0,0.0,100.0
4,101010160101701,1010101601017,1010101601,1,2236.134521,1,1,1,16,1,17,1,MILLET,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,100.0,0.0,4.0,NaN,1.0,3.0,95.0,5.0,0.0,0.0,0.0,0.0,100.0

In [8]:
df11.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
holder_id,9226.0,NaN,NaN,NaN,479901768508368.5625,286516693096911.625,101010160100201.0,305010150415301.0,407040100200203.0,704120090812126.0,1501020310210901.0
household_id,9226.0,NaN,NaN,NaN,4799017685083.675781,2865166930969.116211,1010101601002.0,3050101504153.0,4070401002002.0,7041200908121.25,15010203102109.0
ea_id,9226.0,NaN,NaN,NaN,4799017685.004444,2865166930.972449,1010101601.0,3050101504.0,4070401002.0,7041200908.0,15010203102.0
rural,9226.0,NaN,NaN,NaN,0.97106,0.167647,0.0,1.0,1.0,1.0,1.0
pw,9226.0,NaN,NaN,NaN,3964.290647,2789.748278,91.094223,1668.341797,3720.594971,5539.594238,17094.660156
saq01,9226.0,NaN,NaN,NaN,4.732062,2.859789,1.0,3.0,4.0,7.0,15.0
saq02,9226.0,NaN,NaN,NaN,6.641773,5.402911,1.0,2.0,5.0,9.0,21.0
saq03,9226.0,NaN,NaN,NaN,5.37015,4.242832,1.0,2.0,4.0,8.0,20.0
saq04,9226.0,NaN,NaN,NaN,13.694125,17.160435,1.0,6.0,11.0,18.0,403.0
saq05,9226.0,NaN,NaN,NaN,2.997073,2.135997,1.0,1.0,3.0,4.0,17.0
saq06,9226.0,NaN,NaN,NaN,79.231736,58.60903,1.0,29.0,73.0,122.0,572.0
ph_saq07,9226.0,NaN,NaN,NaN,1.032083,0.279082,1.0,1.0,1.0,1.0,9.0
crop_name,8807,42,MAIZE,1743,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crop_code,8808.0,NaN,NaN,NaN,12.025999,17.83774,0.0,2.0,7.0,13.0,122.0
ph_s11q01,8472.0,NaN,NaN,NaN,1.792021,0.405886,1.0,2.0,2.0,2.0,2.0
ph_s11q02_a,1713,14,N01,1021,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ph_s11q02_b,84,8,N02,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ph_s11q03_a,1752.0,NaN,NaN,NaN,112.024543,294.630912,0.0,20.0,50.0,100.0,8000.0
ph_s11q03_b,1623.0,NaN,NaN,NaN,67.634627,188.141348,0.0,0.0,0.0,0.0,970.0
ph_s11q04_a,1750.0,NaN,NaN,NaN,886.498857,2074.211937,0.0,128.5,300.0,763.75,30120.0
ph_s11q04_b,434.0,NaN,NaN,NaN,4.873272,15.359888,0.0,0.0,1.0,1.0,94.0
ph_s11q05_a,1699.0,NaN,NaN,NaN,1.914067,3.315866,0.0,1.0,1.0,1.0,18.0
ph_s11q05_b,948.0,NaN,NaN,NaN,43.628692,198.006211,1.0,2.0,2.0,2.0,999.0
ph_s11q06_a,1745.0,NaN,NaN,NaN,4.433238,1.360584,0.0,4.0,4.0,5.0,12.0
ph_s11q06_b,1751.0,NaN,NaN,NaN,2001.805254,64.418749,0.0,2004.0,2004.0,2004.0,2004.0
ph_s11q07,1747.0,NaN,NaN,NaN,1.548159,1.112573,0.0,1.0,1.0,2.0,15.0
ph_s11q08,1751.0,NaN,NaN,NaN,3.574529,2.403572,0.0,1.0,3.0,6.0,7.0
ph_s11q09,1618.0,NaN,NaN,NaN,13.821075,67.86651,0.0,0.0,0.0,10.0,2000.0
ph_s11q10_a,7835.0,NaN,NaN,NaN,12.730185,60.667359,0.0,0.0,0.0,0.0,1500.0
ph_s11q10_b,6888.0,NaN,NaN,NaN,9.831591,73.864441,0.0,0.0,0.0,0.0,960.0
ph_s11q11_a,7772.0,NaN,NaN,NaN,0.650669,11.138201,0.0,0.0,0.0,0.0,800.0
ph_s11q11_b,6556.0,NaN,NaN,NaN,1.381178,26.946562,0.0,0.0,0.0,0.0,800.0
ph_s11q12_a,7770.0,NaN,NaN,NaN,0.307722,3.36196,0.0,0.0,0.0,0.0,100.0
ph_s11q12_b,6568.0,NaN,NaN,NaN,2.558161,40.746472,0.0,0.0,0.0,0.0,920.0
ph_s11q13_a,7751.0,NaN,NaN,NaN,0.337763,6.156515,0.0,0.0,0.0,0.0,325.0
ph_s11q13_b,6407.0,NaN,NaN,NaN,0.695021,16.481118,0.0,0.0,0.0,0.0,600.0
ph_s11q14_a,8198.0,NaN,NaN,NaN,18.442303,38.357322,0.0,0.0,8.0,20.0,950.0
ph_s11q14_b,7705.0,NaN,NaN,NaN,66.025568,185.925422,0.0,0.0,0.0,0.0,980.0
ph_s11q15_a,7030.0,NaN,NaN,NaN,1.785206,13.958853,0.0,0.0,0.0,0.0,470.0
ph_s11q15_b,5688.0,NaN,NaN,NaN,3.259494,44.339934,0.0,0.0,0.0,0.0,960.0
ph_s11q15_c,4108.0,NaN,NaN,NaN,4.642892,14.704815,0.0,0.0,0.0,0.0,100.0
ph_s11q16_a,1106.0,NaN,NaN,NaN,3.396926,1.762544,0.0,2.0,3.0,6.0,10.0
ph_s11q16_b,294.0,NaN,NaN,NaN,3.312925,1.680252,0.0,2.0,3.0,4.0,6.0
ph_s11q17,8415.0,NaN,NaN,NaN,1.208318,0.40613,1.0,1.0,1.0,1.0,2.0
ph_s11q18,6542.0,NaN,NaN,NaN,3.456282,1.366435,0.0,3.0,3.0,5.0,50.0
ph_s11q19_a,6621.0,NaN,NaN,NaN,195.726476,328.629734,0.0,30.0,100.0,250.0,7000.0
ph_s11q19_b,6348.0,NaN,NaN,NaN,46.555608,157.395951,0.0,0.0,0.0,0.0,980.0
ph_s11q20_a,6412.0,NaN,NaN,NaN,3.950561,1.788337,0.0,4.0,4.0,5.0,85.0
ph_s11q20_b,1057.0,NaN,NaN,NaN,4.187323,1.480591,0.0,4.0,5.0,5.0,12.0
ph_s11q21_a,7819.0,NaN,NaN,NaN,1.305154,0.923382,0.0,1.0,1.0,1.0,25.0
ph_s11q21_b,6008.0,NaN,NaN,NaN,2.881325,1.664381,0.0,3.0,3.0,3.0,85.0
ph_s11q22_a,8598.0,NaN,NaN,NaN,65.532217,33.233361,0.0,50.0,80.0,90.0,100.0
ph_s11q22_b,8598.0,NaN,NaN,NaN,13.232031,17.320233,0.0,1.0,10.0,20.0,100.0
ph_s11q22_c,8599.0,NaN,NaN,NaN,15.063147,26.995189,0.0,0.0,0.0,20.0,100.0
ph_s11q22_d,8599.0,NaN,NaN,NaN,0.96581,5.926961,0.0,0.0,0.0,0.0,100.0
ph_s11q22_e,8599.0,NaN,NaN,NaN,0.280381,2.926903,0.0,0.0,0.0,0.0,100.0
ph_s11q22_f,8599.0,NaN,NaN,NaN,1.379579,6.809516,0.0,0.0,0.0,0.0,100.0
ph_s11q22_g,8599.0,NaN,NaN,NaN,96.413188,18.58748,0.0,100.0,100.0,100.0,100.0

### Missingness across all PH sections

Columns that are mostly non-null and numeric with plausible quantity ranges are the best candidates for a loss/quantity variable.

In [9]:
for name, df in ph_frames.items():
    print(f"\n--- {name} ---")
    print(df.isna().mean().sort_values().round(3))

--- sect10_ph_w1 ---
holder_id       0.000
saq06           0.000
saq05           0.000
saq04           0.000
saq03           0.000
                ...
ph_s10q02_la    0.995
ph_s10q02_z     0.995
ph_s10q02_na    0.996
ph_s10q02_oa    0.996
ph_s10q02_pa    0.996
Length: 64, dtype: float64

--- sect11_ph_w1 ---
holder_id       0.000
ph_saq07        0.000
saq06           0.000
saq05           0.000
saq03           0.000
saq02           0.000
saq04           0.000
pw              0.000
rural           0.000
ea_id           0.000
household_id    0.000
saq01           0.000
crop_code       0.045
crop_name       0.045
ph_s11q22_c     0.068
ph_s11q22_e     0.068
ph_s11q22_d     0.068
ph_s11q22_f     0.068
ph_s11q22_g     0.068
ph_s11q22_b     0.068
ph_s11q22_a     0.068
ph_s11q01       0.082
ph_s11q17       0.088
ph_s11q14_a     0.111
ph_s11q10_a     0.151
ph_s11q21_a     0.153
ph_s11q11_a     0.158
ph_s11q12_a     0.158
ph_s11q13_a     0.160
ph_s11q14_b     0.165
ph_s11q15_a     0.238
ph_s11q10_b     0.253
ph_s11q19_a     0.282
ph_s11q12_b     0.288
ph_s11q11_b     0.289
ph_s11q18       0.291
ph_s11q20_a     0.305
ph_s11q13_b     0.306
ph_s11q19_b     0.312
ph_s11q21_b     0.349
ph_s11q15_b     0.383
ph_s11q15_c     0.555
ph_s11q03_a     0.810
ph_s11q08       0.810
ph_s11q06_b     0.810
ph_s11q04_a     0.810
ph_s11q07       0.811
ph_s11q06_a     0.811
ph_s11q02_a     0.814
ph_s11q05_a     0.816
ph_s11q03_b     0.824
ph_s11q09       0.825
ph_s11q16_a     0.880
ph_s11q20_b     0.885
ph_s11q05_b     0.897
ph_s11q04_b     0.953
ph_s11q16_b     0.968
ph_s11q02_b     0.991
dtype: float64

--- sect12_ph_w1 ---
holder_id       0.000
household_id    0.000
ea_id           0.000
rural           0.000
pw              0.000
saq01           0.000
saq02           0.000
saq03           0.000
saq04           0.000
saq05           0.000
saq06           0.000
ph_saq07        0.000
crop_code       0.111
crop_name       0.111
ph_s12q14       0.161
ph_s12q10       0.162
ph_s12q04       0.167
ph_s12q06       0.169
ph_s12q02_a     0.188
ph_s12q02_b     0.190
ph_s12q02_c     0.193
ph_s12q02_d     0.193
ph_s12q03       0.196
ph_s12q08       0.750
ph_s12q07       0.753
ph_s12q09_a     0.754
ph_s12q17       0.852
ph_s12q16       0.852
ph_s12q05       0.854
ph_s12q15       0.855
ph_s12q18       0.887
ph_s12q19_a     0.890
ph_s12q19_g     0.890
ph_s12q19_f     0.890
ph_s12q19_b     0.890
ph_s12q19_c     0.890
ph_s12q19_d     0.890
ph_s12q19_e     0.890
ph_s12q11       0.933
ph_s12q13       0.934
ph_s12q12       0.935
ph_s12q09_b     0.972
dtype: float64

--- sect1_ph_w1 ---
individual_id    0.000
ph_s1q00         0.000
ph_saq07         0.000
saq06            0.000
saq05            0.000
saq04            0.000
saq02            0.000
saq03            0.000
pw               0.000
rural            0.000
ea_id            0.000
household_id     0.000
holder_id        0.000
saq01            0.000
ph_s1q03         0.002
ph_s1q02         0.003
ph_s1q04         0.007
ph_s1q05         0.788
dtype: float64

--- sect9_ph_w1 ---
holder_id       0.000
ph_saq07        0.000
saq06           0.000
saq05           0.000
saq03           0.000
saq02           0.000
saq01           0.000
saq04           0.000
parcel_id       0.000
pw              0.000
rural           0.000
ea_id           0.000
household_id    0.000
field_id        0.000
crop_code       0.001
ph_s9q01        0.346
crop_name       0.439
ph_s9q09        0.446
ph_s9q06        0.472
ph_s9q12_a      0.477
ph_s9q07        0.480
ph_s9q13_a      0.483
ph_s9q13_b      0.487
ph_s9q12_b      0.494
ph_s9q02_a      0.560
ph_s9q02_b      0.560
ph_s9q03_b      0.561
ph_s9q04_a      0.569
ph_s9q04_b      0.569
ph_s9q05_b      0.570
ph_s9q03_a      0.619
ph_s9q05_a      0.627
ph_s9q10        0.764
ph_s9q11        0.764
ph_s9q08_a      0.938
ph_s9q08_b      0.969
dtype: float64

--- sect_cover_ph_w1 ---
holder_id     0.0
ph_saq10      0.0
ph_saq07      0.0
saq06         0.0
saq05         0.0
             ...
ph_saq21_j    1.0
ph_saq21_i    1.0
ph_saq21_h    1.0
ph_saq21_f    1.0
ph_saq21_l    1.0
Length: 109, dtype: float64

--- sect_nr_ph_w1 ---
holder_id       0.000
household_id    0.000
ea_id           0.000
rural           0.000
pw              0.000
saq01           0.000
saq02           0.000
saq03           0.000
saq04           0.000
saq05           0.000
saq06           0.000
ph_saq07        0.000
ph_snrq00       0.229
ph_snrq03       0.237
ph_snrq02       0.245
dtype: float64

## Next steps

- [ ] Identify which `ph_sXXqYY` column(s) represent quantity harvested vs. quantity lost/spoiled
- [ ] Cross-check candidate columns against `sect_cover_ph_w1` (interview metadata) and `crop_name`/`crop_code`
- [ ] Once identified, aggregate to household/region level and merge with CHIRPS rainfall data on region + year
- [ ] If a codebook becomes available, replace this blind exploration with confirmed variable mappings

## Part 2 — Verified file roles & crop-level merge

Checking actual column content (crop lists, value ranges, percentage-sum patterns) against the originally assumed file roles turned up several corrections:

| File | Assumed role | Verified role |
|---|---|---|
| `sect1_hh_w1` | household + region identifier | Household **person roster** (age, sex, ...) + region codes. Region codes (`saq01`-`06`) actually exist identically in every PH file below, not just this one. |
| `sect1_ph_w1` | post-harvest crop list | **Not crop data** — no `crop_name` column at all. It's a person roster for the PH module respondent. |
| `sect_nr_ph_w1` | post-harvest non-roster details | Confirmed-ish: holder IDs for people *not* in the household roster. No crop/loss info. |
| `sect9_ph_w1` | crop disposition (sold/stored/lost) | **Storage** detail for field crops (cereals/pulses/oilseeds) — quantity/unit pairs, not disposition. |
| `sect10_ph_w1` | crop loss quantities + reasons | **Confirmed.** 9 lettered columns are 3 (occurred-flag, unit, quantity) triplets = 3 loss-reason slots per crop. |
| `sect11_ph_w1` | tree/root crops post-harvest | Field crops (same scope as sect9). Contains `q22_a`-`g`, percentages summing to ~100 — this is the **disposition breakdown** (sold/consumed/stored/lost shares). |
| `sect12_ph_w1` | storage type used | Garden/perennial crops (fruit, veg, spice). Same %-share disposition structure as sect11, for the garden-crop domain. This is the "tree/root/garden crop" file, not "storage type". |

**Grain mismatch:** `sect9`/`sect10` are one row per household-parcel-field-crop; `sect11`/`sect12` are one row per household-crop (already aggregated across parcels). `sect1_hh_w1` is one row per person. Merging all of these directly on `household_id` would fan out crop rows across household members. Plan:

1. Load only the 5 files that carry crop/loss/person signal: `sect9`, `sect10`, `sect11`, `sect12`, `sect1_hh`.
2. Rename columns to human-readable names — confirmed meanings get real names; everything still ambiguous keeps an honest generic name (`_unconfirmed`) rather than a guessed one, since inventing labels here would be actively misleading without the official LSMS codebook.
3. Aggregate `sect9` and `sect10` up to household+crop grain (sum across parcels/fields).
4. Concatenate `sect11` (field crops) + `sect12` (garden crops) into one disposition table.
5. Outer-merge storage + loss + disposition on `household_id` + `crop_code` + `crop_name`.
6. Attach household-level info (household size, rural flag, region codes) from `sect1_hh_w1`, aggregated to one row per household.

In [10]:
# Geographic hierarchy (saq01-06) follows the standard published ERSS/LSMS-ISA
# Ethiopia admin coding (region > zone > woreda > town > kebele > ea). Kept as
# *_code, not decoded to names, since we don't have the region/zone code lookup.
GEO_RENAME = {
    "saq01": "region_code",
    "saq02": "zone_code",
    "saq03": "woreda_code",
    "saq04": "town_code",
    "saq05": "kebele_code",
    "saq06": "ea_code_local",
    "ea_id": "ea_id",
    "rural": "is_rural",
    "pw": "sampling_weight",
    "household_id": "household_id",
    "holder_id": "holder_id",
    "crop_name": "crop_name",
    "crop_code": "crop_code",
}

# --- sect9: storage detail (field crops) ---
# q01 is binary-like (stored y/n). q02-q05 and q08/q12/q13 are (quantity, unit)
# pairs but WHICH storage attribute each pair measures isn't decodable without
# the codebook, so they keep generic sequential names rather than guessed ones.
SECT9_RENAME = {
    **GEO_RENAME,
    "parcel_id": "parcel_id",
    "field_id": "field_id",
    "ph_s9q01": "storage_flag_unconfirmed",
    "ph_s9q02_a": "storage_qty1_unconfirmed", "ph_s9q02_b": "storage_qty1_unit_unconfirmed",
    "ph_s9q03_a": "storage_qty2_unconfirmed", "ph_s9q03_b": "storage_qty2_unit_unconfirmed",
    "ph_s9q04_a": "storage_qty3_unconfirmed", "ph_s9q04_b": "storage_qty3_unit_unconfirmed",
    "ph_s9q05_a": "storage_qty4_unconfirmed", "ph_s9q05_b": "storage_qty4_unit_unconfirmed",
    "ph_s9q06": "storage_flag2_unconfirmed",
    "ph_s9q07": "storage_flag3_unconfirmed",
    "ph_s9q08_a": "storage_qty5_unconfirmed", "ph_s9q08_b": "storage_qty5_unit_unconfirmed",
    "ph_s9q09": "storage_flag4_unconfirmed",
    "ph_s9q10": "storage_detail1_unconfirmed",
    "ph_s9q11": "storage_detail2_unconfirmed",
    "ph_s9q12_a": "storage_qty6_unconfirmed", "ph_s9q12_b": "storage_qty6_unit_unconfirmed",
    "ph_s9q13_a": "storage_qty7_unconfirmed", "ph_s9q13_b": "storage_qty7_unit_unconfirmed",
}

# --- sect10: loss reasons + quantities (all crop domains) --- CONFIRMED structure:
# 3 reason "slots", each a (occurred, unit, quantity) triplet. Which specific
# reason (pest/rain/theft/...) each slot represents is not decodable without
# the codebook, so slots are numbered, not named by cause.
SECT10_RENAME = {
    **GEO_RENAME,
    "parcel_id": "parcel_id",
    "field_id": "field_id",
    "crop_id": "crop_instance_id",
    "ph_s10q01_a": "loss_reason1_occurred", "ph_s10q01_b": "loss_reason1_unit", "ph_s10q01_c": "loss_reason1_qty",
    "ph_s10q01_d": "loss_reason2_occurred", "ph_s10q01_e": "loss_reason2_unit", "ph_s10q01_f": "loss_reason2_qty",
    "ph_s10q01_g": "loss_reason3_occurred", "ph_s10q01_h": "loss_reason3_unit", "ph_s10q01_i": "loss_reason3_qty",
}
# q02 (33 cols) and q03 (6 cols) blocks: pattern not confidently decoded, kept generic
for c in [f"ph_s10q02_{s}" for s in "abcdefghijklmnopqrstuvwxyz"] + [f"ph_s10q02_{s}a" for s in "klmnop"]:
    SECT10_RENAME[c] = f"loss_detail_{c.split('_')[-1]}_unconfirmed"
for s in "abcdef":
    SECT10_RENAME[f"ph_s10q03_{s}"] = f"loss_extra_{s}_unconfirmed"

# --- sect11 / sect12: disposition share breakdown ---
# q22 (sect11) / q19 (sect12), columns a-f are percentage shares of the crop's
# disposition that sum to ~100; the final letter (g) is a total/check column.
# Exact category per share (sold/consumed/seed/...) is not decodable without
# the codebook.
def disposition_rename(question_prefix):
    d = {**GEO_RENAME}
    letters = "abcdefg"
    for i, l in enumerate(letters[:6], start=1):
        d[f"{question_prefix}_{l}"] = f"disposition_share{i}_pct_unconfirmed"
    d[f"{question_prefix}_g"] = "disposition_total_check_pct"
    return d

SECT11_RENAME = {**GEO_RENAME, **disposition_rename("ph_s11q22")}
SECT12_RENAME = {**GEO_RENAME, **disposition_rename("ph_s12q19")}

# --- sect1_hh: household roster --- CONFIRMED: q00=person number, q03=sex, q04_a=age
SECT1_HH_RENAME = {
    **GEO_RENAME,
    "individual_id": "individual_id",
    "hh_s1q00": "person_number",
    "hh_s1q03": "sex",
    "hh_s1q04_a": "age",
}

df9 = pd.read_csv(DATA_DIR / "sect9_ph_w1.csv").rename(columns=SECT9_RENAME)
df10 = pd.read_csv(DATA_DIR / "sect10_ph_w1.csv").rename(columns=SECT10_RENAME)
df11 = pd.read_csv(DATA_DIR / "sect11_ph_w1.csv").rename(columns=SECT11_RENAME)
df12 = pd.read_csv(DATA_DIR / "sect12_ph_w1.csv").rename(columns=SECT12_RENAME)
df1_hh = pd.read_csv(DATA_DIR / "sect1_hh_w1.csv").rename(columns=SECT1_HH_RENAME)

df9.shape, df10.shape, df11.shape, df12.shape, df1_hh.shape

((7750, 36), (21249, 64), (9226, 58), (7872, 42), (18865, 35))

### Aggregate parcel/field-level files up to household + crop grain

`sect9` (storage) and `sect10` (loss) have one row per parcel/field within a crop; `sect11`/`sect12` (disposition) are already one row per household-crop. Sum the numeric quantity columns across parcels/fields so every table ends up at the same `household_id` + `crop_code` grain.

In [11]:
GRAIN = ["household_id", "crop_code", "crop_name"]

# Identifier/geo/weight columns are numeric but must NOT be summed across
# parcels/fields (they're constant per household, not additive quantities).
NON_ADDITIVE_COLS = {
    "holder_id", "ea_id", "parcel_id", "field_id", "crop_instance_id",
    "region_code", "zone_code", "woreda_code", "town_code", "kebele_code",
    "ea_code_local", "is_rural", "sampling_weight",
}

def agg_to_crop_grain(df, grain=GRAIN):
    numeric_cols = df.select_dtypes("number").columns.difference(grain + list(NON_ADDITIVE_COLS))
    agg = df.groupby(grain, dropna=False)[list(numeric_cols)].sum(min_count=1)
    return agg.reset_index()

storage_agg = agg_to_crop_grain(df9)
loss_agg = agg_to_crop_grain(df10)

# Engineered convenience column: total quantity lost across the 3 reason slots.
# Safe to sum because all three are the same "qty" field by construction (verified
# structure), regardless of which specific reason each slot represents.
loss_agg["total_loss_qty"] = loss_agg[
    ["loss_reason1_qty", "loss_reason2_qty", "loss_reason3_qty"]
].sum(axis=1, min_count=1)

storage_agg.shape, loss_agg.shape

((5700, 24), (13990, 52))

### Combine disposition tables (field crops + garden crops)

In [12]:
df11["crop_domain"] = "field_crop"
df12["crop_domain"] = "garden_crop"

disposition_cols = GRAIN + ["crop_domain"] + [
    c for c in df11.columns if c.startswith("disposition_")
]
disposition_all = pd.concat(
    [df11[disposition_cols], df12[disposition_cols]],
    ignore_index=True,
)

# sect11/sect12 are already one row per household-crop, but guard against
# duplicate interviews by keeping the first record per household+crop.
disposition_all = disposition_all.drop_duplicates(subset=GRAIN, keep="first")

disposition_all.shape

(16690, 11)

### Household-level summary (from the person roster)

`sect1_hh_w1` is per-person; collapse it to one row per household (size + region/rural flags) before attaching it to the crop-level table.

In [13]:
household_summary = (
    df1_hh.groupby("household_id")
    .agg(
        household_size=("person_number", "count"),
        region_code=("region_code", "first"),
        zone_code=("zone_code", "first"),
        woreda_code=("woreda_code", "first"),
        is_rural=("is_rural", "first"),
    )
    .reset_index()
)

household_summary.shape

(3969, 6)

### Final merge: one row per household + crop

In [14]:
crop_loss_master = disposition_all.merge(
    storage_agg, on=GRAIN, how="outer", suffixes=("", "_storage")
).merge(
    loss_agg, on=GRAIN, how="outer", suffixes=("", "_loss")
).merge(
    household_summary, on="household_id", how="left"
)
crop_loss_master["survey_year"] = 2011

print(crop_loss_master.shape)
crop_loss_master.head()

(19894, 87)

,household_id,crop_code,crop_name,crop_domain,disposition_share1_pct_unconfirmed,disposition_share2_pct_unconfirmed,disposition_share3_pct_unconfirmed,disposition_share4_pct_unconfirmed,disposition_share5_pct_unconfirmed,disposition_share6_pct_unconfirmed,disposition_total_check_pct,ph_saq07,storage_detail1_unconfirmed,storage_detail2_unconfirmed,storage_flag2_unconfirmed,storage_flag3_unconfirmed,storage_flag4_unconfirmed,storage_flag_unconfirmed,storage_qty1_unconfirmed,storage_qty1_unit_unconfirmed,storage_qty2_unconfirmed,storage_qty2_unit_unconfirmed,storage_qty3_unconfirmed,storage_qty3_unit_unconfirmed,storage_qty4_unconfirmed,storage_qty4_unit_unconfirmed,storage_qty5_unconfirmed,storage_qty5_unit_unconfirmed,storage_qty6_unconfirmed,storage_qty6_unit_unconfirmed,storage_qty7_unconfirmed,storage_qty7_unit_unconfirmed,loss_detail_a_unconfirmed,loss_detail_b_unconfirmed,loss_detail_c_unconfirmed,loss_detail_d_unconfirmed,loss_detail_e_unconfirmed,loss_detail_f_unconfirmed,loss_detail_g_unconfirmed,loss_detail_h_unconfirmed,loss_detail_i_unconfirmed,loss_detail_j_unconfirmed,loss_detail_k_unconfirmed,loss_detail_ka_unconfirmed,loss_detail_l_unconfirmed,loss_detail_la_unconfirmed,loss_detail_m_unconfirmed,loss_detail_ma_unconfirmed,loss_detail_n_unconfirmed,loss_detail_na_unconfirmed,loss_detail_o_unconfirmed,loss_detail_oa_unconfirmed,loss_detail_p_unconfirmed,loss_detail_pa_unconfirmed,loss_detail_q_unconfirmed,loss_detail_r_unconfirmed,loss_detail_s_unconfirmed,loss_detail_t_unconfirmed,loss_detail_u_unconfirmed,loss_detail_v_unconfirmed,loss_detail_w_unconfirmed,loss_detail_x_unconfirmed,loss_detail_y_unconfirmed,loss_detail_z_unconfirmed,loss_extra_a_unconfirmed,loss_extra_b_unconfirmed,loss_extra_c_unconfirmed,loss_extra_d_unconfirmed,loss_extra_e_unconfirmed,loss_extra_f_unconfirmed,loss_reason1_occurred,loss_reason1_qty,loss_reason1_unit,loss_reason2_occurred,loss_reason2_qty,loss_reason2_unit,loss_reason3_occurred,loss_reason3_qty,loss_reason3_unit,ph_saq07_loss,total_loss_qty,household_size,region_code,zone_code,woreda_code,is_rural,survey_year
0,1010101601002,2.0,MAIZE,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2.0,NaN,8,1,1,1,1,2011
1,1010101601002,3.0,MILLET,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,2.0,NaN,NaN,2.0,2.0,2.0,1.0,8.0,2.0,0.0,200.0,23.0,2.0,0.0,200.0,NaN,NaN,200.0,0.0,2.0,2.0,2.0,3.0,3.0,10.0,1.0,2.0,3.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,8,1,1,1,1,2011
2,1010101601002,6.0,SORGHUM,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,1.0,NaN,NaN,2.0,2.0,2.0,1.0,30.0,2.0,0.0,900.0,15.0,3.0,0.0,810.0,NaN,NaN,600.0,0.0,2.0,3.0,3.0,3.0,7.0,20.0,3.0,3.0,7.0,20.0,3.0,1.0,3.0,NaN,10.0,NaN,4.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2.0,120.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,2.0,120.0,8,1,1,1,1,2011
3,1010101601002,38.0,RED PEPPER,garden_crop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,3.0,NaN,8,1,1,1,1,2011
4,1010101601017,2.0,MAIZE,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,7,1,1,1,1,2011

In [15]:
# Sanity checks
print("rows with a crop from disposition but no loss record:",
      crop_loss_master["total_loss_qty"].isna().sum())
print("rows with total_loss_qty > 0:", (crop_loss_master["total_loss_qty"] > 0).sum())
print("crop_domain counts:")
print(crop_loss_master["crop_domain"].value_counts(dropna=False))
crop_loss_master.describe(include="all").T

rows with a crop from disposition but no loss record: 17217
rows with total_loss_qty > 0: 958
crop_domain counts:
crop_domain
field_crop     9138
garden_crop    7552
NaN            3204
Name: count, dtype: int64

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
household_id,19894.0,NaN,NaN,NaN,5349490433933.525391,2858448412685.883301,1010101601002.0,3070801402191.0,4180701106128.0,7090600104099.0,15010203102109.0
crop_code,18880.0,NaN,NaN,NaN,35.635593,31.440007,0.0,7.0,26.0,63.0,123.0
crop_name,16674,95,MAIZE,1789,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crop_domain,16690,2,field_crop,9138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disposition_share1_pct_unconfirmed,9388.0,NaN,NaN,NaN,66.176502,33.573853,0.0,50.0,80.0,95.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...
region_code,19894.0,NaN,NaN,NaN,5.27928,2.855141,1.0,3.0,4.0,7.0,15.0
zone_code,19894.0,NaN,NaN,NaN,6.968835,5.564159,1.0,2.0,5.0,10.0,21.0
woreda_code,19894.0,NaN,NaN,NaN,5.20559,4.226289,1.0,2.0,4.0,8.0,21.0
is_rural,19894.0,NaN,NaN,NaN,0.968885,0.173633,0.0,1.0,1.0,1.0,1.0
survey_year,19894.0,NaN,NaN,NaN,2011.0,0.0,2011.0,2011.0,2011.0,2011.0,2011.0

In [16]:
OUT_PATH = Path("../data/processed/crop_loss_master_2011.csv")
crop_loss_master.to_csv(OUT_PATH, index=False)
print(f"saved {crop_loss_master.shape} to {OUT_PATH}")

saved (19894, 87) to ../data/processed/crop_loss_master_2011.csv

## Caveats

- Columns suffixed `_unconfirmed` are structurally grouped (e.g. all 3 loss-reason triplets, all 6 disposition shares) but their exact real-world meaning (which reason, which disposition channel) is **not** verified — that requires the official LSMS-ISA Basic Information Document / questionnaire, which isn't in this repo yet.
- `region_code`/`zone_code`/`woreda_code` follow the standard published ERSS admin hierarchy convention but aren't decoded to actual place names (no lookup table available yet).
- `sect_nr_ph_w1` and `sect1_ph_w1` were intentionally excluded from the merge — they carry no crop or loss information (respondent-roster only).
- `crop_loss_master` is Wave 1 (2011-12) only. Repeat this pipeline per wave once Waves 2-5 are added to `data/raw/`, then concatenate before merging with CHIRPS rainfall.

## Part 3 — Wave 2 (2013-14)

Same pipeline, same 7 assumed file roles, applied to Wave 2. Two format differences from Wave 1:

1. Files are **SPSS `.sav`**, not CSV — loaded with `pandas.read_spss` (via `pyreadstat`).
2. SPSS value labels are **auto-decoded** — e.g. `saq01` (region) already reads `"Tigray"`, `"Amhara"`, ... instead of a numeric code, and `crop_code` already reads `"MAIZE"`, `"TEFF"`, ... More free human-readable columns than Wave 1, but not everything is labeled (loss-reason and disposition-channel codes are still raw numbers).

| File | Assumed role | Verified role |
|---|---|---|
| `sect1_hh_w2` | household + region identifier | Confirmed: person roster (`hh_s1q00`=person number, `hh_s1q02`=relationship to head **already text**, `hh_s1q03`=sex **already text**, `hh_s1q04_a`=age) + region. Same caveat as Wave 1 — region/geo codes exist in every file below. |
| `sect1_ph_w2` | post-harvest crop list | **Not crop data**, same as Wave 1 — a PH-module respondent roster, no crop column. |
| `sectnr_ph_w2` | post-harvest non-roster details | Same as Wave 1 — non-roster holder IDs, no crop/loss info. |
| `sect9_ph_w2` | crop disposition (sold/stored/lost) | **Role changed from Wave 1.** Now general crop/parcel characteristics (`ph_s9q01` = cropping pattern, "PURE STAND"/"MIXED STAND", already text) — not storage or disposition. |
| *(new)* `sect9a_ph_w2` | — | **The real storage-detail file** — direct analog of Wave 1's `sect9_ph_w1` (same quantity/date-pair structure). Wave 2 split Wave 1's single section into two; using `sect9a` for the storage role instead of `sect9`. |
| `sect10_ph_w2` | crop loss quantities + reasons | **Confirmed**, same triplet structure as Wave 1. Reason codes still raw numbers. |
| `sect11_ph_w2` | tree/root crops post-harvest | Same as Wave 1: field crops, and `ph_s11q22_a`-`g` is the confirmed disposition % breakdown. **Not** tree/root crops. |
| `sect12_ph_w2` | storage type used | Same as Wave 1: garden/perennial crops with an analogous disposition % structure. **Not** storage type. |

**Column names match Wave 1's `crop_loss_master` schema exactly** (reindexed to it at the end), so this and every later wave's output stays directly concatenable. Two data-quality fixes are needed here that Wave 1 didn't need:

- **Categorical groupby blow-up:** `pandas.read_spss` returns every labeled column (crop_code, region_code, ...) as a `Categorical`. Grouping by a `Categorical` with `dropna=False` enumerates *every* category combination, including unused ones — this silently exploded memory during development. Fixed by casting all categorical columns to plain strings before grouping.
- **Blank `household_id` rows:** a genuine data-quality issue in the raw SPSS export — a small number of rows (257 in `sect10`, 119 in `sect11`, 83 in `sect12`, 5,248 in `sect1_hh`) have a blank (not `NaN`) `household_id`. Left in, `dropna=False` groups them into one bogus mega-household. Dropped before aggregating.

In [17]:
DATA_DIR_W2 = Path("../data/raw/ETH_2013_ESS_v03_M_SPSS")
sorted(p.name for p in DATA_DIR_W2.glob("*.sav"))[:10]

['Crop_CF_Wave2.sav',
 'ET_local_area_unit_conversion.sav',
 'Food_CF_Wave2.sav',
 'Pub_ETH_HouseholdGeovars_Y2.sav',
 'Pub_ETH_PlotGeovariables_Y2.sav',
 'cons_agg_w2.sav',
 'sect10_hh_w2.sav',
 'sect10_ph_w2.sav',
 'sect10a1_com_w2.sav',
 'sect10a2_com_w2.sav']

In [18]:
# The 86-column schema every later wave gets reindexed to, captured from
# Wave 1's finished output (minus survey_year, added separately per wave).
BASE_SCHEMA = [c for c in crop_loss_master.columns if c != "survey_year"]

GEO_RENAME_W2 = {
    "saq01": "region_code", "saq02": "zone_code", "saq03": "woreda_code",
    "saq04": "town_code", "saq05": "kebele_code", "saq06": "ea_code_local",
    "rural": "is_rural", "pw2": "sampling_weight",
    "household_id": "household_id", "holder_id": "holder_id", "ea_id": "ea_id",
    "crop_name": "crop_name", "crop_code": "crop_code",
}

# sect9a (storage): q02/q04 verified as (day, month) date pairs -- unused
# here since Wave 1's slots are quantity/unit, not dates -- the two clean
# quantity pairs (q03, q05) map to storage_qty1/2.
SECT9A_RENAME_W2 = {
    **GEO_RENAME_W2, "parcel_id": "parcel_id", "field_id": "field_id",
    "ph_s9q01": "storage_flag_unconfirmed",
    "ph_s9q03_a": "storage_qty1_unit_unconfirmed", "ph_s9q03_b": "storage_qty1_unconfirmed",
    "ph_s9q05_a": "storage_qty2_unit_unconfirmed", "ph_s9q05_b": "storage_qty2_unconfirmed",
}

# sect10 (loss): CONFIRMED identical triplet/lettering structure to Wave 1.
SECT10_RENAME_W2 = {
    **GEO_RENAME_W2, "parcel_id": "parcel_id", "field_id": "field_id",
    "ph_s10q01_a": "loss_reason1_occurred", "ph_s10q01_b": "loss_reason1_unit", "ph_s10q01_c": "loss_reason1_qty",
    "ph_s10q01_d": "loss_reason2_occurred", "ph_s10q01_e": "loss_reason2_unit", "ph_s10q01_f": "loss_reason2_qty",
    "ph_s10q01_g": "loss_reason3_occurred", "ph_s10q01_h": "loss_reason3_unit", "ph_s10q01_i": "loss_reason3_qty",
}
for c in [f"ph_s10q02_{s}" for s in "abcdefghijklmnopqrstuvwxyz"] + [f"ph_s10q02_{s}a" for s in "klmnop"]:
    SECT10_RENAME_W2[c] = f"loss_detail_{c.split('_')[-1]}_unconfirmed"
for s in "abcdef":
    SECT10_RENAME_W2[f"ph_s10q03_{s}"] = f"loss_extra_{s}_unconfirmed"


def disposition_rename_w2(question_prefix, letters):
    d = {**GEO_RENAME_W2}
    for i, l in enumerate(letters[:-1], start=1):
        d[f"{question_prefix}_{l}"] = f"disposition_share{i}_pct_unconfirmed"
    d[f"{question_prefix}_{letters[-1]}"] = "disposition_total_check_pct"
    return d


SECT11_RENAME_W2 = {**GEO_RENAME_W2, **disposition_rename_w2("ph_s11q22", "abcdefg")}
SECT12_RENAME_W2 = {**GEO_RENAME_W2, **disposition_rename_w2("ph_s12q19", "abcefgh")}  # skips letter 'd'

SECT1_HH_RENAME_W2 = {
    **GEO_RENAME_W2, "individual_id": "individual_id",
    "hh_s1q00": "person_number", "hh_s1q03": "sex", "hh_s1q04_a": "age",
}

df9a_w2 = pd.read_spss(DATA_DIR_W2 / "sect9a_ph_w2.sav").rename(columns=SECT9A_RENAME_W2)
df10_w2 = pd.read_spss(DATA_DIR_W2 / "sect10_ph_w2.sav").rename(columns=SECT10_RENAME_W2)
df11_w2 = pd.read_spss(DATA_DIR_W2 / "sect11_ph_w2.sav").rename(columns=SECT11_RENAME_W2)
df12_w2 = pd.read_spss(DATA_DIR_W2 / "sect12_ph_w2.sav").rename(columns=SECT12_RENAME_W2)
df1_hh_w2 = pd.read_spss(DATA_DIR_W2 / "sect1_hh_w2.sav").rename(columns=SECT1_HH_RENAME_W2)

# Blank (not NaN) household_id rows -- see Part 3 header. Drop before anything
# else touches these frames.
for _name in ["df9a_w2", "df10_w2", "df11_w2", "df12_w2", "df1_hh_w2"]:
    _frame = globals()[_name]
    _before = len(_frame)
    _frame = _frame[_frame["household_id"].astype(str).str.strip() != ""]
    _dropped = _before - len(_frame)
    if _dropped:
        print(f"{_name}: dropped {_dropped} rows with blank household_id")
    globals()[_name] = _frame

# sect9a/sect10 only carry crop_code (already decoded to crop-name text);
# sect11/sect12 carry both crop_name and crop_code (identical text). Backfill
# whichever is missing so all four have both, then de-dup the resulting
# duplicate columns on sect11/sect12.
for _name in ["df9a_w2", "df10_w2", "df11_w2", "df12_w2"]:
    _frame = globals()[_name]
    if "crop_code" not in _frame.columns and "crop_name" in _frame.columns:
        _frame["crop_code"] = _frame["crop_name"]
    if "crop_name" not in _frame.columns and "crop_code" in _frame.columns:
        _frame["crop_name"] = _frame["crop_code"]
    if _frame.columns.duplicated().any():
        globals()[_name] = _frame.loc[:, ~_frame.columns.duplicated()]

# Categorical groupby blow-up fix -- see Part 3 header. Cast every
# pandas.read_spss Categorical column to plain string before any groupby.
for _name in ["df9a_w2", "df10_w2", "df11_w2", "df12_w2", "df1_hh_w2"]:
    _frame = globals()[_name]
    for c in _frame.select_dtypes("category").columns:
        _frame[c] = _frame[c].astype(str).replace("nan", pd.NA)

# region_code comes through SPSS-decoded as region-NAME text (e.g. "Afar")
# for this wave only; map back to the same numeric code every other wave
# uses (confirmed via sect1_hh_w2's saq01 value labels), so region_code is
# a consistent int across all 5 waves' output.
REGION_NAME_TO_CODE_W2 = {
    "Tigray": 1, "Afar": 2, "Amhara": 3, "Oromia": 4, "Somalie": 5,
    "Benshagul Gumuz": 6, "SNNP": 7, "Gambelia": 12, "Harari": 13,
    "Addis Ababa": 14, "Diredwa": 15,
}
for _name in ["df9a_w2", "df10_w2", "df11_w2", "df12_w2", "df1_hh_w2"]:
    _frame = globals()[_name]
    if "region_code" in _frame.columns:
        _frame["region_code"] = _frame["region_code"].map(REGION_NAME_TO_CODE_W2).astype("Int64")

# is_rural: Wave 1 was already 0/1; Wave 2's `rural` decodes to text
# ("Rural"/"Small town (urban)"/"Large town (urban)") -- collapse to the
# same binary semantics as Wave 1.
for _name in ["df9a_w2", "df10_w2", "df11_w2", "df12_w2", "df1_hh_w2"]:
    _frame = globals()[_name]
    if "is_rural" in _frame.columns:
        _frame["is_rural"] = (_frame["is_rural"].astype(str) == "Rural").astype(int)

df9a_w2.shape, df10_w2.shape, df11_w2.shape, df12_w2.shape, df1_hh_w2.shape

df10_w2: dropped 257 rows with blank household_id
df11_w2: dropped 119 rows with blank household_id
df12_w2: dropped 83 rows with blank household_id
df1_hh_w2: dropped 5248 rows with blank household_id

((3532, 31), (29318, 77), (9355, 82), (7442, 61), (20910, 75))

In [19]:
GRAIN_W2 = ["household_id", "crop_code", "crop_name"]
NON_ADDITIVE_COLS_W2 = {
    "holder_id", "ea_id", "parcel_id", "field_id",
    "region_code", "zone_code", "woreda_code", "town_code", "kebele_code",
    "ea_code_local", "is_rural", "sampling_weight",
}

def agg_to_crop_grain_w2(df, grain=GRAIN_W2):
    numeric_cols = df.select_dtypes("number").columns.difference(grain + list(NON_ADDITIVE_COLS_W2))
    return df.groupby(grain, dropna=False)[list(numeric_cols)].sum(min_count=1).reset_index()

storage_agg_w2 = agg_to_crop_grain_w2(df9a_w2)
loss_agg_w2 = agg_to_crop_grain_w2(df10_w2)

loss_agg_w2["total_loss_qty"] = loss_agg_w2[
    ["loss_reason1_qty", "loss_reason2_qty", "loss_reason3_qty"]
].sum(axis=1, min_count=1)

storage_agg_w2.shape, loss_agg_w2.shape

((3335, 12), (17863, 61))

In [20]:
df11_w2["crop_domain"] = "field_crop"
df12_w2["crop_domain"] = "garden_crop"

disposition_cols_w2 = GRAIN_W2 + ["crop_domain"] + [
    c for c in df11_w2.columns if c.startswith("disposition_")
]
disposition_all_w2 = pd.concat(
    [df11_w2[disposition_cols_w2], df12_w2[disposition_cols_w2]],
    ignore_index=True,
)
disposition_all_w2 = disposition_all_w2.drop_duplicates(subset=GRAIN_W2, keep="first")

household_summary_w2 = (
    df1_hh_w2.groupby("household_id")
    .agg(
        household_size=("person_number", "count"),
        region_code=("region_code", "first"),
        zone_code=("zone_code", "first"),
        woreda_code=("woreda_code", "first"),
        is_rural=("is_rural", "first"),
    )
    .reset_index()
)

crop_loss_master_w2 = (
    disposition_all_w2.merge(storage_agg_w2, on=GRAIN_W2, how="outer", suffixes=("", "_storage"))
    .merge(loss_agg_w2, on=GRAIN_W2, how="outer", suffixes=("", "_loss"))
    .merge(household_summary_w2, on="household_id", how="left")
)

dupes = [c for c in crop_loss_master_w2.columns if c.endswith("_x") or c.endswith("_y")]
assert not dupes, f"duplicate-suffixed columns: {dupes}"

print(crop_loss_master_w2.shape)
crop_loss_master_w2.head()

(18305, 83)

,household_id,crop_code,crop_name,crop_domain,disposition_share1_pct_unconfirmed,disposition_share2_pct_unconfirmed,disposition_share3_pct_unconfirmed,disposition_share4_pct_unconfirmed,disposition_share5_pct_unconfirmed,disposition_share6_pct_unconfirmed,disposition_total_check_pct,ph_s9q00,ph_s9q02_a,ph_s9q04_a,ph_s9q0a,ph_saq07,storage_qty1_unconfirmed,storage_qty1_unit_unconfirmed,storage_qty2_unconfirmed,storage_qty2_unit_unconfirmed,hh_saq02,hh_saq03,hh_saq04,hh_saq05,hh_saq06,hh_saq07,hh_saq08,loss_detail_a_unconfirmed,loss_detail_b_unconfirmed,loss_detail_c_unconfirmed,loss_detail_d_unconfirmed,loss_detail_e_unconfirmed,loss_detail_f_unconfirmed,loss_detail_g_unconfirmed,loss_detail_h_unconfirmed,loss_detail_i_unconfirmed,loss_detail_j_unconfirmed,loss_detail_k_unconfirmed,loss_detail_ka_unconfirmed,loss_detail_l_unconfirmed,loss_detail_la_unconfirmed,loss_detail_m_unconfirmed,loss_detail_ma_unconfirmed,loss_detail_n_unconfirmed,loss_detail_na_unconfirmed,loss_detail_o_unconfirmed,loss_detail_oa_unconfirmed,loss_detail_p_unconfirmed,loss_detail_pa_unconfirmed,loss_detail_q_unconfirmed,loss_detail_r_unconfirmed,loss_detail_s_unconfirmed,loss_detail_t_unconfirmed,loss_detail_u_unconfirmed,loss_detail_v_unconfirmed,loss_detail_w_unconfirmed,loss_detail_x_unconfirmed,loss_detail_y_unconfirmed,loss_detail_z_unconfirmed,loss_extra_a_unconfirmed,loss_extra_b_unconfirmed,loss_extra_c_unconfirmed,loss_extra_d_unconfirmed,loss_extra_e_unconfirmed,loss_extra_f_unconfirmed,loss_reason1_occurred,loss_reason1_qty,loss_reason1_unit,loss_reason2_occurred,loss_reason2_qty,loss_reason2_unit,loss_reason3_occurred,loss_reason3_qty,loss_reason3_unit,ph_s10q00a,ph_s10q00b,ph_saq07_loss,total_loss_qty,household_size,region_code,zone_code,woreda_code,is_rural
0,01010101601002,MAIZE,MAIZE,field_crop,43.0,0.0,0.0,28.0,0.0,29.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,8.0,88.0,16.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,1.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,2.0,2.0,NaN,9.0,1,1.0,1.0,1.0
1,01010101601002,MILLET,MILLET,field_crop,25.0,0.0,0.0,7.0,0.0,68.0,100.0,1.0,23.0,8.0,6.0,2.0,120.0,3.0,100.0,3.0,1.0,1.0,8.0,88.0,16.0,1.0,2.0,2.0,1.0,1.0,10.0,3.0,1.0,1.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,6.0,2.0,NaN,9.0,1,1.0,1.0,1.0
2,01010101601002,RED PEPPER,RED PEPPER,garden_crop,12.0,0.0,0.0,0.0,63.0,25.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,16.0,176.0,32.0,2.0,4.0,6.0,2.0,2.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2.0,8.0,4.0,NaN,9.0,1,1.0,1.0,1.0
3,01010101601002,SESAME,SESAME,field_crop,0.0,0.0,0.0,11.0,89.0,0.0,100.0,2.0,14.0,29.0,1.0,2.0,380.0,1.0,340.0,1.0,1.0,1.0,8.0,88.0,16.0,1.0,2.0,2.0,1.0,4.0,11.0,1.0,1.0,1.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2.0,1.0,2.0,NaN,9.0,1,1.0,1.0,1.0
4,01010101601002,SORGHUM,SORGHUM,field_crop,10.0,0.0,0.0,0.0,30.0,60.0,100.0,1.0,26.0,10.0,4.0,2.0,30.0,2.0,0.0,2.0,3.0,3.0,24.0,264.0,48.0,3.0,6.0,6.0,3.0,17.0,28.0,6.0,2.0,8.0,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,3.0,19.0,6.0,NaN,9.0,1,1.0,1.0,1.0

In [21]:
# Reindex to Wave 1's exact column set (any Wave-1-only column with no Wave 2
# equivalent comes back all-NaN, which is expected -- see Part 3 header).
crop_loss_master_w2 = crop_loss_master_w2.reindex(columns=BASE_SCHEMA)
assert list(crop_loss_master_w2.columns) == BASE_SCHEMA
crop_loss_master_w2["survey_year"] = 2013

# Sanity checks
print("nan household_id:", crop_loss_master_w2["household_id"].isna().sum())
print("rows with total_loss_qty > 0:", (crop_loss_master_w2["total_loss_qty"] > 0).sum())
print("crop_domain counts:")
print(crop_loss_master_w2["crop_domain"].value_counts(dropna=False))
print("household_size describe:")
print(crop_loss_master_w2["household_size"].describe())

OUT_PATH_W2 = Path("../data/processed/crop_loss_master_2013.csv")
crop_loss_master_w2.to_csv(OUT_PATH_W2, index=False)
print(f"\nsaved {crop_loss_master_w2.shape} to {OUT_PATH_W2}")

nan household_id: 0
rows with total_loss_qty > 0: 1091
crop_domain counts:
crop_domain
field_crop     9198
garden_crop    7241
NaN            1866
Name: count, dtype: int64
household_size describe:
count    18294.000000
mean         6.113207
std          2.318472
min          1.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         16.000000
Name: household_size, dtype: float64

saved (18305, 87) to ../data/processed/crop_loss_master_2013.csv

## Part 4 — Wave 3 (2015-16)

Wave 3's raw files are organized into subfolders (`Community/`, `Household/`, `Post-Harvest/`, `Post-Planting/`) rather than one flat directory, but the file set and structure inside `Post-Harvest/` mirror Wave 2 almost exactly: `sect9a_ph_w3` is the storage file (same date/quantity-pair structure), `sect10_ph_w3` has the same confirmed loss triplet, `sect11_ph_w3`/`sect12_ph_w3` have the same disposition % structure. Unlike Wave 2, this is a **plain CSV export with no embedded value labels** — `region_code`, `is_rural` etc. are raw numeric codes, same as Wave 1.

One real difference: `sect9a_ph_w3` has **no `crop_name` column at all** (only numeric `crop_code`, unlike Wave 2 where `crop_code` was already decoded to text). Backfilling `crop_name` from `crop_code` the way Wave 2 does would put a raw number where a name belongs, so storage is aggregated on `crop_code` alone here and joined into the rest on that narrower key.

In [22]:
DATA_DIR_W3 = Path("../data/raw/ETH_2015_ESS_v03_M_CSV")
PH_DIR_W3 = DATA_DIR_W3 / "Post-Harvest"
HH_DIR_W3 = DATA_DIR_W3 / "Household"
sorted(p.name for p in PH_DIR_W3.glob("*.csv"))

['sect10_ph_w3.csv',
 'sect11_ph_w3.csv',
 'sect12_ph_w3.csv',
 'sect1_ph_w3.csv',
 'sect9_ph_w3.csv',
 'sect9a_ph_w3.csv',
 'sect_cover_cc_w3.csv',
 'sect_cover_ph_w3.csv',
 'sectnr_ph_w3.csv']

In [23]:
GEO_RENAME_W3 = {
    "saq01": "region_code", "saq02": "zone_code", "saq03": "woreda_code",
    "saq04": "town_code", "saq05": "kebele_code", "saq06": "ea_code_local",
    "ea_id": "ea_id", "rural": "is_rural", "pw_w3": "sampling_weight",
    "household_id": "household_id", "holder_id": "holder_id",
    "crop_name": "crop_name", "crop_code": "crop_code",
}

# sect9a: same (day/month, unit/qty) pair structure as Wave 2's sect9a.
SECT9A_RENAME_W3 = {
    **GEO_RENAME_W3, "parcel_id": "parcel_id", "field_id": "field_id",
    "ph_s9q00": "storage_flag_unconfirmed",
    "ph_s9q01_a": "storage_qty1_unconfirmed", "ph_s9q01_b": "storage_qty1_unit_unconfirmed",
    "ph_s9q02_a": "storage_qty2_unconfirmed", "ph_s9q02_b": "storage_qty2_unit_unconfirmed",
    "ph_s9q03_a": "storage_qty3_unconfirmed", "ph_s9q03_b": "storage_qty3_unit_unconfirmed",
    "ph_s9q04_a": "storage_qty4_unconfirmed", "ph_s9q04_b": "storage_qty4_unit_unconfirmed",
    "ph_s9q05_a": "storage_qty5_unconfirmed", "ph_s9q05_b": "storage_qty5_unit_unconfirmed",
}

# sect10: CONFIRMED identical triplet/lettering structure to Wave 1/2.
SECT10_RENAME_W3 = {
    **GEO_RENAME_W3, "parcel_id": "parcel_id", "field_id": "field_id",
    "ph_s10q01_a": "loss_reason1_occurred", "ph_s10q01_b": "loss_reason1_unit", "ph_s10q01_c": "loss_reason1_qty",
    "ph_s10q01_d": "loss_reason2_occurred", "ph_s10q01_e": "loss_reason2_unit", "ph_s10q01_f": "loss_reason2_qty",
    "ph_s10q01_g": "loss_reason3_occurred", "ph_s10q01_h": "loss_reason3_unit", "ph_s10q01_i": "loss_reason3_qty",
}
for c in [f"ph_s10q02_{s}" for s in "abcdefghijklmnop"]:
    SECT10_RENAME_W3[c] = f"loss_detail_{c.split('_')[-1]}_unconfirmed"
for s in "abcdef":
    SECT10_RENAME_W3[f"ph_s10q03_{s}"] = f"loss_extra_{s}_unconfirmed"


def disposition_rename_w3(question_prefix, letters):
    d = {**GEO_RENAME_W3}
    for i, l in enumerate(letters[:-1], start=1):
        d[f"{question_prefix}_{l}"] = f"disposition_share{i}_pct_unconfirmed"
    d[f"{question_prefix}_{letters[-1]}"] = "disposition_total_check_pct"
    return d


SECT11_RENAME_W3 = {**GEO_RENAME_W3, **disposition_rename_w3("ph_s11q22", "abcdefg")}
SECT12_RENAME_W3 = {**GEO_RENAME_W3, **disposition_rename_w3("ph_s12q19", "abcefgh")}  # skips letter 'd', same as Wave 2

SECT1_HH_RENAME_W3 = {
    **GEO_RENAME_W3, "individual_id": "individual_id",
    "hh_s1q00": "person_number", "hh_s1q03": "sex", "hh_s1q04a": "age",
}

df9a_w3 = pd.read_csv(PH_DIR_W3 / "sect9a_ph_w3.csv").rename(columns=SECT9A_RENAME_W3)
df10_w3 = pd.read_csv(PH_DIR_W3 / "sect10_ph_w3.csv").rename(columns=SECT10_RENAME_W3)
df11_w3 = pd.read_csv(PH_DIR_W3 / "sect11_ph_w3.csv").rename(columns=SECT11_RENAME_W3)
df12_w3 = pd.read_csv(PH_DIR_W3 / "sect12_ph_w3.csv").rename(columns=SECT12_RENAME_W3)
df1_hh_w3 = pd.read_csv(HH_DIR_W3 / "sect1_hh_w3.csv").rename(columns=SECT1_HH_RENAME_W3)

# Guard against the same blank/missing household_id issue found in Wave 2,
# even though Wave 3's household_id is numeric here (so it shows as NaN,
# not a blank string).
for _name in ["df9a_w3", "df10_w3", "df11_w3", "df12_w3", "df1_hh_w3"]:
    _frame = globals()[_name]
    _before = len(_frame)
    _frame = _frame[_frame["household_id"].notna()]
    _dropped = _before - len(_frame)
    if _dropped:
        print(f"{_name}: dropped {_dropped} rows with missing household_id")
    globals()[_name] = _frame

df9a_w3.shape, df10_w3.shape, df11_w3.shape, df12_w3.shape, df1_hh_w3.shape

df10_w3: dropped 1 rows with missing household_id

((5647, 29), (30321, 49), (8167, 64), (7335, 52), (27990, 66))

In [24]:
# sect9a has no crop_name column (numeric crop_code only) -- aggregate
# storage on crop_code alone and join it in on that narrower key below.
GRAIN_STORAGE_W3 = ["household_id", "crop_code"]
GRAIN_W3 = ["household_id", "crop_code", "crop_name"]
NON_ADDITIVE_COLS_W3 = {
    "holder_id", "ea_id", "parcel_id", "field_id",
    "region_code", "zone_code", "woreda_code", "town_code", "kebele_code",
    "ea_code_local", "is_rural", "sampling_weight",
}

def agg_to_crop_grain_w3(df, grain):
    numeric_cols = df.select_dtypes("number").columns.difference(grain + list(NON_ADDITIVE_COLS_W3))
    return df.groupby(grain, dropna=False)[list(numeric_cols)].sum(min_count=1).reset_index()

storage_agg_w3 = agg_to_crop_grain_w3(df9a_w3, GRAIN_STORAGE_W3)
loss_agg_w3 = agg_to_crop_grain_w3(df10_w3, GRAIN_W3)
loss_agg_w3["total_loss_qty"] = loss_agg_w3[
    ["loss_reason1_qty", "loss_reason2_qty", "loss_reason3_qty"]
].sum(axis=1, min_count=1)

df11_w3["crop_domain"] = "field_crop"
df12_w3["crop_domain"] = "garden_crop"
disposition_cols_w3 = GRAIN_W3 + ["crop_domain"] + [c for c in df11_w3.columns if c.startswith("disposition_")]
disposition_all_w3 = pd.concat([df11_w3[disposition_cols_w3], df12_w3[disposition_cols_w3]], ignore_index=True)
disposition_all_w3 = disposition_all_w3.drop_duplicates(subset=GRAIN_W3, keep="first")

household_summary_w3 = (
    df1_hh_w3.groupby("household_id")
    .agg(
        household_size=("person_number", "count"),
        region_code=("region_code", "first"),
        zone_code=("zone_code", "first"),
        woreda_code=("woreda_code", "first"),
        is_rural=("is_rural", "first"),
    )
    .reset_index()
)

crop_loss_master_w3 = (
    disposition_all_w3.merge(storage_agg_w3, on=GRAIN_STORAGE_W3, how="outer", suffixes=("", "_storage"))
    .merge(loss_agg_w3, on=GRAIN_W3, how="outer", suffixes=("", "_loss"))
    .merge(household_summary_w3, on="household_id", how="left")
)

dupes = [c for c in crop_loss_master_w3.columns if c.endswith("_x") or c.endswith("_y")]
assert not dupes, f"duplicate-suffixed columns: {dupes}"

print(crop_loss_master_w3.shape)
crop_loss_master_w3.head()

(18414, 65)

,household_id,crop_code,crop_name,crop_domain,disposition_share1_pct_unconfirmed,disposition_share2_pct_unconfirmed,disposition_share3_pct_unconfirmed,disposition_share4_pct_unconfirmed,disposition_share5_pct_unconfirmed,disposition_share6_pct_unconfirmed,disposition_total_check_pct,household_id2,obs,ph_s9q0a,ph_saq07,storage_flag_unconfirmed,storage_qty1_unit_unconfirmed,storage_qty2_unconfirmed,storage_qty2_unit_unconfirmed,storage_qty3_unconfirmed,storage_qty3_unit_unconfirmed,storage_qty4_unconfirmed,storage_qty4_unit_unconfirmed,storage_qty5_unconfirmed,storage_qty5_unit_unconfirmed,household_id2_loss,loss_detail_a_unconfirmed,loss_detail_b_unconfirmed,loss_detail_c_unconfirmed,loss_detail_d_unconfirmed,loss_detail_e_unconfirmed,loss_detail_f_unconfirmed,loss_detail_g_unconfirmed,loss_detail_h_unconfirmed,loss_detail_i_unconfirmed,loss_detail_j_unconfirmed,loss_detail_k_unconfirmed,loss_detail_l_unconfirmed,loss_detail_m_unconfirmed,loss_detail_n_unconfirmed,loss_detail_o_unconfirmed,loss_detail_p_unconfirmed,loss_extra_a_unconfirmed,loss_extra_b_unconfirmed,loss_extra_c_unconfirmed,loss_extra_d_unconfirmed,loss_extra_e_unconfirmed,loss_extra_f_unconfirmed,loss_reason1_occurred,loss_reason1_qty,loss_reason1_unit,loss_reason2_occurred,loss_reason2_qty,loss_reason2_unit,loss_reason3_occurred,loss_reason3_qty,loss_reason3_unit,obs_loss,ph_saq07_loss,total_loss_qty,household_size,region_code,zone_code,woreda_code,is_rural
0,1.010102e+12,2,MAIZE,field_crop,100.0,0.0,0.0,0.0,0.0,0.0,100.0,1.010109e+16,1.0,2.0,1.0,1.0,2.0,4.0,2.0,1.0,340.0,19.0,2.0,1.0,250.0,1.010109e+16,1.0,2.0,1.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,1.0,NaN,8.0,1.0,1.0,1.0,1.0
1,1.010102e+12,6,SORGHUM,field_crop,75.0,0.0,0.0,1.0,24.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.010109e+16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,0.0,NaN,0.0,NaN,4.0,80.0,4.0,2.0,80.0,2.0,0.0,NaN,NaN,3.0,1.0,160.0,8.0,1.0,1.0,1.0,1.0
2,1.010102e+12,38,RED PEPPER,garden_crop,100.0,0.0,0.0,0.0,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.010109e+16,1.0,1.0,1.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2.0,1.0,NaN,8.0,1.0,1.0,1.0,1.0
3,1.010102e+12,2,MAIZE,field_crop,67.0,0.0,0.0,33.0,0.0,0.0,100.0,1.010109e+16,1.0,2.0,1.0,1.0,2.0,5.0,2.0,0.0,420.0,20.0,2.0,0.0,410.0,1.010109e+16,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,7.0,1.0,1.0,2.0,0.0,2.0,2.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,1.0,NaN,9.0,1.0,1.0,1.0,1.0
4,1.010102e+12,3,MILLET,field_crop,50.0,0.0,0.0,50.0,0.0,0.0,100.0,1.010109e+16,2.0,4.0,1.0,1.0,3.0,22.0,2.0,0.0,360.0,7.0,3.0,0.0,340.0,1.010109e+16,1.0,1.0,3.0,9.0,2.0,1.0,1.0,5.0,4.0,1.0,1.0,5.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,3.0,1.0,NaN,9.0,1.0,1.0,1.0,1.0

In [25]:
crop_loss_master_w3 = crop_loss_master_w3.reindex(columns=BASE_SCHEMA)
assert list(crop_loss_master_w3.columns) == BASE_SCHEMA
crop_loss_master_w3["survey_year"] = 2015

print("nan household_id:", crop_loss_master_w3["household_id"].isna().sum())
print("rows with total_loss_qty > 0:", (crop_loss_master_w3["total_loss_qty"] > 0).sum())
print("household_size describe:")
print(crop_loss_master_w3["household_size"].describe())

OUT_PATH_W3 = Path("../data/processed/crop_loss_master_2015.csv")
crop_loss_master_w3.to_csv(OUT_PATH_W3, index=False)
print(f"\nsaved {crop_loss_master_w3.shape} to {OUT_PATH_W3}")

nan household_id: 0
rows with total_loss_qty > 0: 1190
household_size describe:
count    18348.000000
mean         6.630368
std          2.450415
min          1.000000
25%          5.000000
50%          7.000000
75%          8.000000
max         17.000000
Name: household_size, dtype: float64

saved (18414, 87) to ../data/processed/crop_loss_master_2015.csv

## Part 5 — Waves 4 & 5 (2018-19, 2021-22)

Waves 4-5 use a **substantially redesigned questionnaire**: no more `ph_` prefix (`s10q01a` instead of `ph_s10q01_a`), and crop identity is no longer a separate `crop_code`/`crop_name` pair — it's baked inline into a single text field as `"N. CROPNAME"` (e.g. `s9q00b` = `"6. SORGHUM"`), which gets split into numeric code + name here.

- **Storage (`sect9`) and loss (`sect10`) are solid.** `sect10`'s `s10q01a`-`i` has the exact same confirmed 3×(occurred, unit, qty) triplet structure as every earlier wave. Crop identity comes through cleanly as English text.
- **Disposition (`sect11`) had to be dropped for these two waves.** It only carries `harvestedcrop_id` (a small integer) and its own crop-name field, which is mostly garbled Amharic-script text with a few inconsistent romanized entries. `harvestedcrop_id` doesn't resolve back to `sect9`'s crop list either — `sect9`'s crop numbering resets per field, so the join is ambiguous for the majority of rows. Decided with the user to leave `disposition_share*`/`crop_domain` empty for 2018 and 2021 rather than attach them to unreliable crop names.
- Several Wave 1-3 `storage_*_unconfirmed` slots don't have an obvious analog in the redesigned `sect9` and are left empty for these two waves — only the flag (`s9q04`) and one clean quantity field (`s9q05a`) map cleanly.
- `household_id` representation is inconsistent across files within these waves too (int in some, zero-padded string in others) — normalized through a numeric round-trip before any merge, the same fix needed during development (a naive string cast would leave a leading-zero mismatch that silently fails every join).

In [26]:
import re

LABEL_RE = re.compile(r"^\s*(\d+)\.\s*(.+?)\s*$")


def split_code_label(series):
    """'6. SORGHUM' -> (6, 'SORGHUM'); leaves non-matching values as (NaN, original)."""
    codes, labels = [], []
    for v in series:
        if pd.isna(v):
            codes.append(pd.NA)
            labels.append(pd.NA)
            continue
        m = LABEL_RE.match(str(v))
        if m:
            codes.append(int(m.group(1)))
            labels.append(m.group(2).upper())
        else:
            codes.append(pd.NA)
            labels.append(str(v).upper())
    return pd.Series(codes, index=series.index), pd.Series(labels, index=series.index)


def build_wave_redesigned(wave_suffix, data_dir, survey_year):
    """Shared pipeline for Waves 4 (2018) and 5 (2021)."""
    print(f"\n{'='*20} Wave {survey_year} ({wave_suffix}) {'='*20}")

    geo_rename = {
        "saq01": "region_code", "saq02": "zone_code", "saq03": "woreda_code",
        "saq04": "town_code", "saq05": "kebele_code", "saq06": "ea_code_local",
        "ea_id": "ea_id", "saq14": "is_rural", f"pw_{wave_suffix}": "sampling_weight",
        "household_id": "household_id", "holder_id": "holder_id",
    }
    sect9_rename = {
        **geo_rename, "parcel_id": "parcel_id", "field_id": "field_id",
        "s9q04": "storage_flag_unconfirmed",
        "s9q05a": "storage_qty1_unconfirmed",
    }
    sect10_rename = {
        **geo_rename, "parcel_id": "parcel_id", "field_id": "field_id",
        "s10q01a": "loss_reason1_occurred", "s10q01b": "loss_reason1_unit", "s10q01c": "loss_reason1_qty",
        "s10q01d": "loss_reason2_occurred", "s10q01e": "loss_reason2_unit", "s10q01f": "loss_reason2_qty",
        "s10q01g": "loss_reason3_occurred", "s10q01h": "loss_reason3_unit", "s10q01i": "loss_reason3_qty",
    }
    for l in "abcdefghijklmnop":
        sect10_rename[f"s10q02{l}"] = f"loss_detail_{l}_unconfirmed"
    for l in "abcdef":
        sect10_rename[f"s10q03{l}"] = f"loss_extra_{l}_unconfirmed"

    df9 = pd.read_csv(data_dir / f"sect9_ph_{wave_suffix}.csv", low_memory=False).rename(columns=sect9_rename)
    df10 = pd.read_csv(data_dir / f"sect10_ph_{wave_suffix}.csv", low_memory=False).rename(columns=sect10_rename)
    df1_hh = pd.read_csv(data_dir / f"sect1_hh_{wave_suffix}.csv", low_memory=False).rename(columns=geo_rename)

    # household_id dtype varies file-to-file (int64 in some files, a
    # zero-padded string in others). A numeric round-trip (pd.to_numeric ->
    # Int64) silently downcasts these ~17-digit IDs to float64 first and
    # loses precision (float64 only holds integers exactly up to 2**53),
    # corrupting most IDs. Normalize as pure strings instead: strip
    # whitespace, drop a trailing ".0" left by any prior float cast, then
    # strip leading zeros so padded and unpadded forms match.
    def normalize_household_id(s):
        return s.astype(str).str.strip().str.replace(r"\.0$", "", regex=True).str.lstrip("0")

    for frame in (df9, df10, df1_hh):
        frame["household_id"] = normalize_household_id(frame["household_id"])

    for name, frame in [("sect9", df9), ("sect10", df10), ("sect1_hh", df1_hh)]:
        before = len(frame)
        frame = frame[frame["household_id"].notna()]
        dropped = before - len(frame)
        if dropped:
            print(f"{name}: dropped {dropped} rows with missing household_id")
        if name == "sect9":
            df9 = frame
        elif name == "sect10":
            df10 = frame
        else:
            df1_hh = frame

    df9["crop_code"], df9["crop_name"] = split_code_label(df9["s9q00b"])
    df10["crop_code"], df10["crop_name"] = split_code_label(df10["s9q00b"])

    for frame in (df9, df10, df1_hh):
        frame["region_code"], _ = split_code_label(frame["region_code"])
        _, rural_label = split_code_label(frame["is_rural"])
        frame["is_rural"] = (rural_label == "RURAL").astype("Int64")

    grain = ["household_id", "crop_code", "crop_name"]
    non_additive = {
        "holder_id", "ea_id", "parcel_id", "field_id",
        "region_code", "zone_code", "woreda_code", "town_code", "kebele_code",
        "ea_code_local", "is_rural", "sampling_weight",
    }

    def agg_to_crop_grain(df):
        numeric_cols = df.select_dtypes("number").columns.difference(grain + list(non_additive))
        return df.groupby(grain, dropna=False)[list(numeric_cols)].sum(min_count=1).reset_index()

    storage_agg = agg_to_crop_grain(df9)
    loss_agg = agg_to_crop_grain(df10)
    loss_agg["total_loss_qty"] = loss_agg[["loss_reason1_qty", "loss_reason2_qty", "loss_reason3_qty"]].sum(axis=1, min_count=1)

    household_summary = (
        df1_hh.groupby("household_id")
        .agg(
            household_size=("individual_id", "count"),
            region_code=("region_code", "first"),
            zone_code=("zone_code", "first"),
            woreda_code=("woreda_code", "first"),
            is_rural=("is_rural", "first"),
        )
        .reset_index()
    )

    crop_loss_master = (
        storage_agg.merge(loss_agg, on=grain, how="outer", suffixes=("", "_loss"))
        .merge(household_summary, on="household_id", how="left")
    )
    # No disposition data for these waves (see Part 5 header).
    crop_loss_master["crop_domain"] = pd.NA

    dupes = [c for c in crop_loss_master.columns if c.endswith("_x") or c.endswith("_y")]
    assert not dupes, f"duplicate-suffixed columns: {dupes}"

    crop_loss_master = crop_loss_master.reindex(columns=BASE_SCHEMA)
    assert list(crop_loss_master.columns) == BASE_SCHEMA
    crop_loss_master["survey_year"] = survey_year

    out_path = Path(f"../data/processed/crop_loss_master_{survey_year}.csv")
    crop_loss_master.to_csv(out_path, index=False)
    print(f"saved {crop_loss_master.shape} -> {out_path}")
    print("nan household_id:", crop_loss_master["household_id"].isna().sum())
    print("rows with total_loss_qty > 0:", (crop_loss_master["total_loss_qty"] > 0).sum())
    print("household_size describe:")
    print(crop_loss_master["household_size"].describe())
    return crop_loss_master


crop_loss_master_w4 = build_wave_redesigned("w4", Path("../data/raw/ETH_2018_ESS_v04_M_CSV"), 2018)
crop_loss_master_w5 = build_wave_redesigned("w5", Path("../data/raw/ETH_2021_ESPS-W5_v02_M_CSV"), 2021)

==================== Wave 2018 (w4) ====================

saved (10275, 87) -> ../data/processed/crop_loss_master_2018.csv
nan household_id: 0
rows with total_loss_qty > 0: 793
household_size describe:
count    9972.000000
mean        5.394605
std         2.241650
min         1.000000
25%         4.000000
50%         5.000000
75%         7.000000
max        19.000000
Name: household_size, dtype: float64

==================== Wave 2021 (w5) ====================

saved (8189, 87) -> ../data/processed/crop_loss_master_2021.csv
nan household_id: 0
rows with total_loss_qty > 0: 850
household_size describe:
count    8188.000000
mean        6.015022
std         2.389085
min         1.000000
25%         4.000000
50%         6.000000
75%         7.000000
max        20.000000
Name: household_size, dtype: float64

## Part 6 — Combine all 5 waves

Every wave's output was already reindexed to the same `BASE_SCHEMA` and tagged with `survey_year`, so concatenating them is a straight `pd.concat`. Re-reading each one from disk (rather than reusing the in-memory frames from Parts 2-5) keeps this step correct even if you only run this cell after a previous session already built the individual files.

This step also normalizes `region_code` to one clean nullable-integer dtype across all 5 waves (each wave's own CSV round-trip could otherwise leave it as a mix of `"1"`/`"1.0"`-style strings) and adds a `region_name` display column alongside it -- see Part 9 for the reasoning.

In [27]:
frames = []
for yr in [2011, 2013, 2015, 2018, 2021]:
    df = pd.read_csv(f"../data/processed/crop_loss_master_{yr}.csv", low_memory=False)
    frames.append(df)
    print(yr, df.shape)

crop_loss_master_all = pd.concat(frames, ignore_index=True, sort=False)

# Each wave's own CSV round-trip can leave region_code as a mix of "1"/"1.0"-style
# strings (float formatting on any column that had NaNs during that wave's own
# save/reload). Force it to one clean nullable-int dtype across all 5 waves so it
# is safe to use as a join key (e.g. for the CHIRPS rainfall merge in Part 9).
crop_loss_master_all["region_code"] = pd.to_numeric(crop_loss_master_all["region_code"], errors="coerce").astype("Int64")

# region_code is the canonical key used for merging/modeling everywhere above;
# region_name is added here purely as a display label for anything user-facing
# (e.g. the mobile app UI) -- see Part 9 for why we keep both instead of one or
# the other.
REGION_CODE_TO_NAME = {
    1: "Tigray", 2: "Afar", 3: "Amhara", 4: "Oromia", 5: "Somali",
    6: "Benishangul-Gumuz", 7: "SNNPR", 12: "Gambela", 13: "Harari",
    14: "Addis Ababa", 15: "Dire Dawa",
}
crop_loss_master_all["region_name"] = crop_loss_master_all["region_code"].map(REGION_CODE_TO_NAME)

crop_loss_master_all.to_csv("../data/processed/crop_loss_master_all.csv", index=False)

print("\ncombined shape:", crop_loss_master_all.shape)
print(crop_loss_master_all["survey_year"].value_counts().sort_index())
print("\nregion_code dtype:", crop_loss_master_all["region_code"].dtype)
print("region_name nulls:", crop_loss_master_all["region_name"].isna().sum())

2011 (19894, 87)
2013 (18305, 87)
2015 (18414, 87)
2018 (10275, 87)
2021 (8189, 87)

combined shape: (75077, 88)
survey_year
2011    19894
2013    18305
2015    18414
2018    10275
2021     8189
Name: count, dtype: int64

region_code dtype: Int64
region_name nulls: 381

## Part 7 — Explore all 5 waves together

`data/processed/crop_loss_master_all.csv` was just rebuilt in Part 6 above from scratch (all 5 waves). This section just re-loads it for exploration — no need to re-merge anything.

In [28]:
df_all = pd.read_csv("../data/processed/crop_loss_master_all.csv", low_memory=False)

print(df_all.shape)
df_all.head()

(75077, 88)

,household_id,crop_code,crop_name,crop_domain,disposition_share1_pct_unconfirmed,disposition_share2_pct_unconfirmed,disposition_share3_pct_unconfirmed,disposition_share4_pct_unconfirmed,disposition_share5_pct_unconfirmed,disposition_share6_pct_unconfirmed,disposition_total_check_pct,ph_saq07,storage_detail1_unconfirmed,storage_detail2_unconfirmed,storage_flag2_unconfirmed,storage_flag3_unconfirmed,storage_flag4_unconfirmed,storage_flag_unconfirmed,storage_qty1_unconfirmed,storage_qty1_unit_unconfirmed,storage_qty2_unconfirmed,storage_qty2_unit_unconfirmed,storage_qty3_unconfirmed,storage_qty3_unit_unconfirmed,storage_qty4_unconfirmed,storage_qty4_unit_unconfirmed,storage_qty5_unconfirmed,storage_qty5_unit_unconfirmed,storage_qty6_unconfirmed,storage_qty6_unit_unconfirmed,storage_qty7_unconfirmed,storage_qty7_unit_unconfirmed,loss_detail_a_unconfirmed,loss_detail_b_unconfirmed,loss_detail_c_unconfirmed,loss_detail_d_unconfirmed,loss_detail_e_unconfirmed,loss_detail_f_unconfirmed,loss_detail_g_unconfirmed,loss_detail_h_unconfirmed,loss_detail_i_unconfirmed,loss_detail_j_unconfirmed,loss_detail_k_unconfirmed,loss_detail_ka_unconfirmed,loss_detail_l_unconfirmed,loss_detail_la_unconfirmed,loss_detail_m_unconfirmed,loss_detail_ma_unconfirmed,loss_detail_n_unconfirmed,loss_detail_na_unconfirmed,loss_detail_o_unconfirmed,loss_detail_oa_unconfirmed,loss_detail_p_unconfirmed,loss_detail_pa_unconfirmed,loss_detail_q_unconfirmed,loss_detail_r_unconfirmed,loss_detail_s_unconfirmed,loss_detail_t_unconfirmed,loss_detail_u_unconfirmed,loss_detail_v_unconfirmed,loss_detail_w_unconfirmed,loss_detail_x_unconfirmed,loss_detail_y_unconfirmed,loss_detail_z_unconfirmed,loss_extra_a_unconfirmed,loss_extra_b_unconfirmed,loss_extra_c_unconfirmed,loss_extra_d_unconfirmed,loss_extra_e_unconfirmed,loss_extra_f_unconfirmed,loss_reason1_occurred,loss_reason1_qty,loss_reason1_unit,loss_reason2_occurred,loss_reason2_qty,loss_reason2_unit,loss_reason3_occurred,loss_reason3_qty,loss_reason3_unit,ph_saq07_loss,total_loss_qty,household_size,region_code,zone_code,woreda_code,is_rural,survey_year,region_name
0,1.010102e+12,2.0,MAIZE,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2.0,NaN,8.0,1.0,1.0,1.0,1.0,2011,Tigray
1,1.010102e+12,3.0,MILLET,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,2.0,NaN,NaN,2.0,2.0,2.0,1.0,8.0,2.0,0.0,200.0,23.0,2.0,0.0,200.0,NaN,NaN,200.0,0.0,2.0,2.0,2.0,3.0,3.0,10.0,1.0,2.0,3.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,8.0,1.0,1.0,1.0,1.0,2011,Tigray
2,1.010102e+12,6.0,SORGHUM,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,1.0,NaN,NaN,2.0,2.0,2.0,1.0,30.0,2.0,0.0,900.0,15.0,3.0,0.0,810.0,NaN,NaN,600.0,0.0,2.0,3.0,3.0,3.0,7.0,20.0,3.0,3.0,7.0,20.0,3.0,1.0,3.0,NaN,10.0,NaN,4.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2.0,120.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,2.0,120.0,8.0,1.0,1.0,1.0,1.0,2011,Tigray
3,1.010102e+12,38.0,RED PEPPER,garden_crop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,3.0,NaN,8.0,1.0,1.0,1.0,1.0,2011,Tigray
4,1.010102e+12,2.0,MAIZE,field_crop,95.0,5.0,0.0,0.0,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,7.0,1.0,1.0,1.0,1.0,2011,Tigray

In [29]:
print("rows per survey_year:")
print(df_all["survey_year"].value_counts().sort_index())

print("\nrows with confirmed loss (total_loss_qty > 0) per year:")
print(df_all[df_all["total_loss_qty"] > 0].groupby("survey_year").size())

print("\ncrop_domain coverage per year (NaN = Waves 4-5, dropped as discussed):")
print(df_all.groupby("survey_year")["crop_domain"].apply(lambda s: s.notna().mean()).round(2))

rows per survey_year:
survey_year
2011    19894
2013    18305
2015    18414
2018    10275
2021     8189
Name: count, dtype: int64

rows with confirmed loss (total_loss_qty > 0) per year:
survey_year
2011     958
2013    1091
2015    1190
2018     793
2021     850
dtype: int64

crop_domain coverage per year (NaN = Waves 4-5, dropped as discussed):
survey_year
2011    0.84
2013    0.90
2015    0.83
2018    0.00
2021    0.00
Name: crop_domain, dtype: float64

## Part 8 — CHIRPS rainfall: explore & select columns for a future merge

Source: `data/raw/CHIRPS/eth-rainfall-subnat-full.csv` (WFP/CHIRPS dekadal rainfall
indicators for Ethiopia, downloaded from data.humdata.org). Raw structure:

- `date`: dekadal (10-day period) observations -- the 1st, 11th, and 21st of every
  month, 1981-present.
- `adm_level` / `adm_id` / `PCODE`: administrative unit. `adm_level=1` is region
  (11 regions, `PCODE` like `ET01`..`ET15`); `adm_level=2` is zone (74 zones,
  `PCODE` like `ET0101`).
- `rfh` / `rfh_avg`: rainfall for the current dekad (mm) and its long-term
  average for that same dekad.
- `r1h` / `r1h_avg`, `r3h` / `r3h_avg`: rolling 1-month and 3-month rainfall
  totals and their long-term averages.
- `rfq` / `r1q` / `r3q`: the current dekad/1-month/3-month rainfall as a
  percentage of its long-term average (i.e. a rainfall anomaly / drought-flood
  indicator).
- `n_pixels`, `version` (`final`/`prelim`): metadata -- pixel count behind the
  spatial average, and whether the estimate is final or a preliminary value
  for the most recent month.

**Region-code crosswalk confirmed**: `sect1_hh_w2`'s SPSS value labels for
`saq01` (region_code) decode exactly as `1=Tigray, 2=Afar, 3=Amhara, 4=Oromia,
5=Somalie, 6=Benshagul Gumuz, 7=SNNP, 12=Gambelia, 13=Harari, 14=Addis Ababa,
15=Diredwa` -- i.e. the LSMS numeric `region_code` used in
`crop_loss_master_all` **is** the numeric suffix of CHIRPS's region `PCODE`
(region_code 14 <-> `ET14`, etc.). No external boundary lookup needed.

This step keeps only region-level rows (`adm_level == 1` -- LSMS's `zone_code`
is a per-region local sequence, not nationally unique, so it can't be matched
to CHIRPS zone PCODEs without more work) and only `final` rows (the CHIRPS
years relevant here, 2011-2021, are all final; `prelim` only covers the most
recent month of the download). Still at dekadal grain -- aggregating to
annual/seasonal rainfall features and actually merging onto
`crop_loss_master_all` is a follow-up step, not done here.

In [30]:
rain_raw = pd.read_csv("../data/raw/CHIRPS/eth-rainfall-subnat-full.csv", low_memory=False)
print("raw shape:", rain_raw.shape)
print(rain_raw.dtypes)

RAINFALL_RENAME = {
    "date": "date",
    "PCODE": "admin_pcode",
    "rfh": "rainfall_dekad_mm",
    "rfh_avg": "rainfall_dekad_avg_mm",
    "r1h": "rainfall_1month_mm",
    "r1h_avg": "rainfall_1month_avg_mm",
    "r3h": "rainfall_3month_mm",
    "r3h_avg": "rainfall_3month_avg_mm",
    "rfq": "rainfall_dekad_pct_of_avg",
    "r1q": "rainfall_1month_pct_of_avg",
    "r3q": "rainfall_3month_pct_of_avg",
    "version": "data_version",
}

rainfall_region = (
    rain_raw[rain_raw["adm_level"] == 1]
    .query("version == \'final\'")
    [list(RAINFALL_RENAME)]
    .rename(columns=RAINFALL_RENAME)
    .copy()
)

rainfall_region["region_code"] = rainfall_region["admin_pcode"].str.replace("ET", "", regex=False).astype(int)
rainfall_region["date"] = pd.to_datetime(rainfall_region["date"])
rainfall_region["year"] = rainfall_region["date"].dt.year
rainfall_region["month"] = rainfall_region["date"].dt.month

rainfall_region = rainfall_region[
    ["date", "year", "month", "region_code", "admin_pcode",
     "rainfall_dekad_mm", "rainfall_dekad_avg_mm", "rainfall_dekad_pct_of_avg",
     "rainfall_1month_mm", "rainfall_1month_avg_mm", "rainfall_1month_pct_of_avg",
     "rainfall_3month_mm", "rainfall_3month_avg_mm", "rainfall_3month_pct_of_avg",
     "data_version"]
]

out_path = Path("../data/processed/rainfall_region_dekadal.csv")
rainfall_region.to_csv(out_path, index=False)
print(f"\nsaved: {rainfall_region.shape} -> {out_path}")
print("\nregion_codes:", sorted(rainfall_region["region_code"].unique()))
print("year range:", rainfall_region["year"].min(), "-", rainfall_region["year"].max())
rainfall_region.head()

raw shape: (149604, 15)
date          object
adm_level      int64
adm_id         int64
PCODE         object
n_pixels     float64
rfh          float64
rfh_avg      float64
r1h          float64
r1h_avg      float64
r3h          float64
r3h_avg      float64
rfq          float64
r1q          float64
r3q          float64
version       object
dtype: object

saved: (18051, 15) -> ../data/processed/rainfall_region_dekadal.csv

region_codes: [1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 15]
year range: 1981 - 2026

,date,year,month,region_code,admin_pcode,rainfall_dekad_mm,rainfall_dekad_avg_mm,rainfall_dekad_pct_of_avg,rainfall_1month_mm,rainfall_1month_avg_mm,rainfall_1month_pct_of_avg,rainfall_3month_mm,rainfall_3month_avg_mm,rainfall_3month_pct_of_avg,data_version
0,1981-01-01,1981,1,14,ET14,1.4,3.641667,74.059790,NaN,NaN,NaN,NaN,NaN,NaN,final
1,1981-01-11,1981,1,14,ET14,1.2,4.305000,66.630844,NaN,NaN,NaN,NaN,NaN,NaN,final
2,1981-01-21,1981,1,14,ET14,1.3,5.723333,58.750390,3.9,13.670000,47.67006,NaN,NaN,NaN,final
3,1981-02-01,1981,2,14,ET14,2.1,11.851666,42.132330,4.6,21.880000,35.71429,NaN,NaN,NaN,final
4,1981-02-11,1981,2,14,ET14,26.5,11.213333,194.284550,29.9,28.788334,103.29009,NaN,NaN,NaN,final

## Part 9 — Aggregate rainfall to season/year and merge into `crop_loss_master_all`

`crop_loss_master_all` has one row per household+crop **per survey wave** (no
exact interview date), so the dekadal rainfall from Part 8 has to be
aggregated up before it can be joined -- by `region_code` and by calendar
year, matched to `survey_year`. Ethiopia has two rainy seasons that matter for
crop outcomes:

- **Belg** (Feb-May): short rains, secondary season in most regions.
- **Meher** (Jun-Sep): main rains, ~90%+ of national production; this is the
  season LSMS's post-harvest questions are mostly asking about.

For each `(region_code, year)` we compute total rainfall (mm) and rainfall as
a % of the long-term average, for Belg, Meher, and the full year, then merge
onto `crop_loss_master_all` on `(region_code, survey_year == year)`.
**Assumption, not confirmed against survey field-dates**: this matches each
wave's rainfall to the same calendar year as `survey_year` (e.g. 2018 crop
loss rows get 2018's Belg/Meher rainfall). LSMS post-harvest interviews are
fielded after the Meher harvest (roughly Sept-Jan), so this should be the
right growing season for most rows, but a household interviewed early in a
wave could in principle be reporting on the *previous* year's Meher. Treat it
the same way as the project's other `_unconfirmed` fields if that matters for
the model.

**Design note on `region_code` vs `region_name` (and the same question for
any other coded field)**: both are kept, on purpose, rather than picking one.
`region_code` is the join/model key everywhere in this pipeline -- it's
stable and unambiguous, whereas the *text* spellings turned out to vary by
source even within this one project (Wave 2's raw SPSS labels alone had
"Somalie"/"Diredwa"/"Benshagul Gumuz" for what a person would call
"Somali"/"Dire Dawa"/"Benishangul-Gumuz" -- see the Wave 2 fix above). For
anything the mobile app actually displays, use `region_name` (or a cleaned
label like it) -- never show a raw numeric code or an internal machine key to
an end user. The same split applies to the rainfall columns here: the model
can consume `rainfall_meher_pct_of_avg` directly, but a UI should show
something like "Meher rainfall: 78% of normal" rather than the column name.
Keep the code as the source of truth for joins/training, and maintain the
human label as a lookup applied only at the display layer -- that way a
relabeling (or a translation) never risks silently breaking a merge.

In [31]:
rainfall_dekadal = pd.read_csv("../data/processed/rainfall_region_dekadal.csv")

SEASON_MONTHS = {
    "belg": range(2, 6),    # Feb-May
    "meher": range(6, 10),  # Jun-Sep
}

def season_agg(df, months, label):
    sub = df[df["month"].isin(months)]
    out = (
        sub.groupby(["region_code", "year"])
        .agg(_total_mm=("rainfall_dekad_mm", "sum"), _avg_mm=("rainfall_dekad_avg_mm", "sum"))
        .reset_index()
    )
    out[f"rainfall_{label}_mm"] = out["_total_mm"]
    out[f"rainfall_{label}_pct_of_avg"] = (out["_total_mm"] / out["_avg_mm"] * 100).round(1)
    return out[["region_code", "year", f"rainfall_{label}_mm", f"rainfall_{label}_pct_of_avg"]]

belg_agg = season_agg(rainfall_dekadal, SEASON_MONTHS["belg"], "belg")
meher_agg = season_agg(rainfall_dekadal, SEASON_MONTHS["meher"], "meher")

annual_agg = (
    rainfall_dekadal.groupby(["region_code", "year"])
    .agg(rainfall_annual_mm=("rainfall_dekad_mm", "sum"), _avg_mm=("rainfall_dekad_avg_mm", "sum"))
    .reset_index()
)
annual_agg["rainfall_annual_pct_of_avg"] = (annual_agg["rainfall_annual_mm"] / annual_agg["_avg_mm"] * 100).round(1)
annual_agg = annual_agg[["region_code", "year", "rainfall_annual_mm", "rainfall_annual_pct_of_avg"]]

rainfall_seasonal = (
    belg_agg.merge(meher_agg, on=["region_code", "year"], how="outer")
    .merge(annual_agg, on=["region_code", "year"], how="outer")
)
rainfall_seasonal["region_code"] = rainfall_seasonal["region_code"].astype("Int64")

crop_loss_master_all = pd.read_csv("../data/processed/crop_loss_master_all.csv", low_memory=False)
crop_loss_master_all["region_code"] = pd.to_numeric(crop_loss_master_all["region_code"], errors="coerce").astype("Int64")

rain_cols = [c for c in rainfall_seasonal.columns if c not in ("region_code", "year")]
crop_loss_master_all = crop_loss_master_all.drop(columns=[c for c in rain_cols if c in crop_loss_master_all.columns])
crop_loss_master_all = crop_loss_master_all.merge(
    rainfall_seasonal, left_on=["region_code", "survey_year"], right_on=["region_code", "year"], how="left"
).drop(columns="year")

crop_loss_master_all.to_csv("../data/processed/crop_loss_master_all.csv", index=False)

print("final shape:", crop_loss_master_all.shape)
print("\nrainfall column null rate by survey_year:")
print(crop_loss_master_all.groupby("survey_year")[rain_cols].apply(lambda g: g.isna().mean()))
print("\nmean Meher rainfall (% of average) by survey_year:")
print(crop_loss_master_all.groupby("survey_year")["rainfall_meher_pct_of_avg"].mean())

final shape: (75077, 94)

rainfall column null rate by survey_year:
             rainfall_belg_mm  rainfall_belg_pct_of_avg  rainfall_meher_mm  \
survey_year
2011                 0.000000                  0.000000           0.000000
2013                 0.000601                  0.000601           0.000601
2015                 0.003584                  0.003584           0.003584
2018                 0.029489                  0.029489           0.029489
2021                 0.000122                  0.000122           0.000122

             rainfall_meher_pct_of_avg  rainfall_annual_mm  \
survey_year
2011                          0.000000            0.000000
2013                          0.000601            0.000601
2015                          0.003584            0.003584
2018                          0.029489            0.029489
2021                          0.000122            0.000122

             rainfall_annual_pct_of_avg
survey_year
2011                           0.000000
2013                           0.000601
2015                           0.003584
2018                           0.029489
2021                           0.000122

mean Meher rainfall (% of average) by survey_year:
survey_year
2011    111.704866
2013    106.016563
2015     87.751864
2018     98.555776
2021    101.514167
Name: rainfall_meher_pct_of_avg, dtype: float64